package lab.zhang.rule.rule_engine.service.impl

import com.baomidou.mybatisplus.core.conditions.query.QueryWrapper
import lab.zhang.rule.rule_engine.entity.ExecutionArrangementEntity
import lab.zhang.rule.rule_engine.enums.ContentTypeEnum
import lab.zhang.rule.rule_engine.enums.RuleStatusEnum
import lab.zhang.rule.rule_engine.mapper.ExecutionArrangementMapper
import lab.zhang.rule.rule_engine.mapper.RuleGroupMapper
import lab.zhang.rule.rule_engine.mapper.RuleMapper
import lab.zhang.rule.rule_engine.model.Rule
import lab.zhang.rule.rule_engine.pojo.dto.RuleDTO
import lab.zhang.rule.rule_engine.service.RuleGroupService
import lab.zhang.rule.rule_engine.service.RuleService
import lab.zhang.rule.rule_engine.util.TimeUtil
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.boot.test.context.SpringBootTest
import org.springframework.test.context.ActiveProfiles
import org.springframework.transaction.annotation.Transactional
import spock.lang.Specification
import spock.lang.Unroll

/**
 * RuleGroupService database integration test
 * Tests business logic with real database operations
 *
 * Prerequisites:
 * 1. MySQL database is running on localhost:3306
 * 2. Database 'rule_engine_test' exists
 * 3. Tables are created (see DATABASE_SCHEMA.md)
 *
 * @author Rongjin Zhang
 */
@SpringBootTest
@ActiveProfiles("test")
@Transactional
class RuleGroupServiceImplDatabaseSpec extends Specification {

    @Autowired
    private RuleService ruleService

    @Autowired
    private RuleGroupService ruleGroupService

    @Autowired
    private RuleMapper ruleMapper

    @Autowired
    private RuleGroupMapper ruleGroupMapper

    @Autowired
    private ExecutionArrangementMapper executionArrangementMapper


    def setup() {
        // Clean up test data before each test
        executionArrangementMapper.delete(null)
        ruleGroupMapper.delete(null)
        ruleMapper.delete(null)
    }

    @Unroll
    def "Business Logic 1: Rule changes from #oldRuleState to #newRuleState - ruleId: #ruleId, eventIds: #eventIds, isGrouped: #isGrouped"() {
        given: "create a rule with initial status"
        // Create rule with the specified initial status
        def rule = createRule("Test Rule", ContentTypeEnum.EXPRESSION, oldRuleState)
        ruleService.createRule(rule)
        def actualRuleId = rule.getId()
        assert actualRuleId != null: "Rule ID should be generated by database"

        and: "create rule and event associations"
        eventIds.eachWithIndex { eventId, index ->
            createRuleEventRelation(eventId, actualRuleId, index + 1)
        }

        and: "check no rule group exists initially"
        def initialGroupId = getRuleGroupByRule(actualRuleId)
        assert initialGroupId == null: "Rule should not be in any group initially. RuleId: ${actualRuleId}, Initial group: ${initialGroupId}"

        when: "update rule status step by step to target status"
        // Always follow the transition path: OFFLINE -> TEST -> GRAY -> ONLINE
        def currentRule = ruleService.getRuleById(actualRuleId)

        // OFFLINE -> TEST (if needed)
        if (newRuleState != RuleStatusEnum.OFFLINE) {
            if (currentRule.getRuleStatus() == RuleStatusEnum.OFFLINE) {
                def ruleToUpdate = createRuleUpdateObject(actualRuleId, RuleStatusEnum.TEST)
                ruleService.updateRule(actualRuleId, ruleToUpdate)
                currentRule = ruleService.getRuleById(actualRuleId)
            }
        }

        // TEST -> GRAY (if needed)
        if (newRuleState == RuleStatusEnum.GRAY || newRuleState == RuleStatusEnum.ONLINE) {
            if (currentRule.getRuleStatus() == RuleStatusEnum.TEST) {
                def ruleToUpdate = createRuleUpdateObject(actualRuleId, RuleStatusEnum.GRAY)
                ruleService.updateRule(actualRuleId, ruleToUpdate)
                currentRule = ruleService.getRuleById(actualRuleId)
            }
        }

        // GRAY -> ONLINE (if needed)
        if (newRuleState == RuleStatusEnum.ONLINE) {
            if (currentRule.getRuleStatus() == RuleStatusEnum.GRAY) {
                def ruleToUpdate = createRuleUpdateObject(actualRuleId, RuleStatusEnum.ONLINE)
                ruleService.updateRule(actualRuleId, ruleToUpdate)
                currentRule = ruleService.getRuleById(actualRuleId)
            }
        }

        then: "check rule group existence matches expected result"
        def finalGroupId = getRuleGroupByRule(actualRuleId)
        if (isGrouped) {
            assert finalGroupId != null && finalGroupId != 0L: "Rule should be in a group. RuleId: ${actualRuleId}, Final group: ${finalGroupId}"
        } else {
            assert finalGroupId == null || finalGroupId == 0L: "Rule should not be in any group. RuleId: ${actualRuleId}, Final group: ${finalGroupId}"
        }

        where:
        ruleId | oldRuleState          | newRuleState           | eventIds          | isGrouped
        null   | RuleStatusEnum.OFFLINE | RuleStatusEnum.TEST   | [1001]            | false
        null   | RuleStatusEnum.OFFLINE | RuleStatusEnum.GRAY   | [1001]            | false
        null   | RuleStatusEnum.OFFLINE | RuleStatusEnum.ONLINE | [1001]            | true
        null   | RuleStatusEnum.TEST    | RuleStatusEnum.GRAY   | [1001]            | false
        null   | RuleStatusEnum.TEST    | RuleStatusEnum.ONLINE | [1001]            | true
        null   | RuleStatusEnum.GRAY    | RuleStatusEnum.ONLINE | [1001]            | true
    }


    @Unroll
    def "Business Logic 2: Rule changes from ONLINE to #newStatus - remove from group - ruleId: #ruleId"() {
        given: "create a rule in ONLINE status in a group"
        def ruleToUpdate
        // First create rule as OFFLINE (new rules are always OFFLINE)
        // Note: ruleId parameter is ignored, database will auto-generate ID
        def rule = createRule("Test Rule", ContentTypeEnum.EXPRESSION, RuleStatusEnum.OFFLINE)
        ruleService.createRule(rule)
        def actualRuleId = rule.getId()
        assert actualRuleId != null: "Rule ID should be generated by database"
        // associate rule with an event
        createRuleEventRelation(eventId, actualRuleId, 0)
        // Then update to ONLINE status (OFFLINE -> TEST -> GRAY -> ONLINE)
        // Follow valid state transition path according to state transition rules:
        // - OFFLINE -> only TEST
        // - TEST -> GRAY or OFFLINE
        // - GRAY -> OFFLINE or ONLINE
        rule = ruleService.getRuleById(actualRuleId)
        assert rule != null: "Rule should exist before transition to TEST"
        assert rule.getRuleStatus() == RuleStatusEnum.OFFLINE: "Rule should be in OFFLINE status. RuleId: ${actualRuleId}, Current status: ${rule.getRuleStatus()}"
        ruleToUpdate = Rule.builder()
                .id(rule.getId())
                .name(rule.getName())
                .contentType(rule.getContentType())
                .content(rule.getContent())
                .description(rule.getDescription())
                .ruleStatus(RuleStatusEnum.TEST)
                .build()
        ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)
        rule = ruleService.getRuleById(actualRuleId)
        assert rule != null: "Rule should exist before transition to GRAY"
        assert rule.getRuleStatus() == RuleStatusEnum.TEST: "Rule should be in TEST status. RuleId: ${actualRuleId}, Current status: ${rule.getRuleStatus()}"
        ruleToUpdate = Rule.builder()
                .id(rule.getId())
                .name(rule.getName())
                .contentType(rule.getContentType())
                .content(rule.getContent())
                .description(rule.getDescription())
                .ruleStatus(RuleStatusEnum.GRAY)
                .build()
        ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)
        rule = ruleService.getRuleById(actualRuleId)
        assert rule != null: "Rule should exist before transition to ONLINE"
        assert rule.getRuleStatus() == RuleStatusEnum.GRAY: "Rule should be in GRAY status. RuleId: ${actualRuleId}, Current status: ${rule.getRuleStatus()}"
        // Now transition to ONLINE
        ruleToUpdate = Rule.builder()
                .id(rule.getId())
                .name(rule.getName())
                .contentType(rule.getContentType())
                .content(rule.getContent())
                .description(rule.getDescription())
                .ruleStatus(RuleStatusEnum.ONLINE)
                .build()
        ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)
        rule = ruleService.getRuleById(actualRuleId)
        // When transitioning to ONLINE, changeRuleStatusToOnline automatically creates a rule group
        // Get the group ID that was created during the transition
        def groupId = getRuleGroupIdForRuleAndEvent(actualRuleId, eventId)
        assert groupId != null && groupId != 0L: "Rule group should be created during ONLINE transition. RuleId: ${actualRuleId}, EventId: ${eventId}"

        when: "change rule status to other status"
        // Re-load rule from database to get the latest state before updating
        rule = ruleService.getRuleById(actualRuleId)
        assert rule != null: "Rule should exist in database before status change. RuleId: ${actualRuleId}"
        assert rule.getRuleStatus() == RuleStatusEnum.ONLINE: "Rule should be in ONLINE status before transitioning to ${newStatus}. RuleId: ${actualRuleId}, Current status: ${rule.getRuleStatus()}"
        assert rule.getRuleStatus().canChangeTo(newStatus): "Transition from ${rule.getRuleStatus()} to ${newStatus} is not allowed. RuleId: ${actualRuleId}"
        // Create a new Rule object with all fields from the loaded rule, but with new status
        ruleToUpdate = Rule.builder()
                .id(rule.getId())
                .name(rule.getName())
                .contentType(rule.getContentType())
                .content(rule.getContent())
                .description(rule.getDescription())
                .ruleStatus(newStatus)
                .build()
        ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)

        // Re-load rule from database to get the latest ruleGroupId (cleared by removeRuleFromGroup)
        rule = ruleService.getRuleById(actualRuleId)

        then: "rule should be removed from group and group should be deleted"
        assert rule != null: "Rule should exist in database after status change. RuleId: ${actualRuleId}"
        // Verify rule is no longer in any group
        // After transitioning from ONLINE, the rule should have group_id = 0 or no records
        def allRuleRelations = executionArrangementMapper.selectList(
                new QueryWrapper<ExecutionArrangementEntity>()
                        .eq("rule_id", actualRuleId)
        )
        def ruleRelationsWithGroup = allRuleRelations.findAll { it.groupId != null && it.groupId != 0L }
        assert ruleRelationsWithGroup.isEmpty(): "Rule should not be in any group after removal. RuleId: ${actualRuleId}, Relations with group: ${ruleRelationsWithGroup.collect { "groupId=${it.groupId}, eventId=${it.eventId}" }}"
        def currentGroupId = getRuleGroupByRule(actualRuleId)
        assert currentGroupId == null: "Rule should not be in any group after removal. RuleId: ${actualRuleId}"

        // Verify rule group entity is deleted (deleteRuleGroup is called in changeRuleStatusFromABTest)
        def groupEntity = ruleGroupMapper.selectById(groupId)
        assert groupEntity == null: "Rule group entity should be deleted after rule status change from ONLINE. GroupId: ${groupId}"

        // Verify rule-group relations are deleted
        def ruleGroupRelations = executionArrangementMapper.selectList(
                new QueryWrapper<ExecutionArrangementEntity>()
                        .eq("group_id", groupId)
        )
        assert ruleGroupRelations == null || ruleGroupRelations.isEmpty(): "Rule-group relations should be deleted. GroupId: ${groupId}"

        // Verify group-event relations are deleted
        def groupEventRelations = executionArrangementMapper.selectList(
                new QueryWrapper<ExecutionArrangementEntity>()
                        .eq("group_id", groupId)
        )
        assert groupEventRelations == null || groupEventRelations.isEmpty(): "Group-event relations should be deleted. GroupId: ${groupId}"

        where:
        eventId | ruleId | newStatus
        1001    | null   | RuleStatusEnum.OFFLINE
    }

    @Unroll
    def "Business Logic 2: Rule changes from ONLINE to #invalidStatus should throw exception - ruleId: #ruleId"() {
        given: "create a rule in ONLINE status in a group"
        def ruleToUpdate
        // First create rule as OFFLINE (new rules are always OFFLINE)
        def rule = createRule("Test Rule", ContentTypeEnum.EXPRESSION, RuleStatusEnum.OFFLINE)
        ruleService.createRule(rule)
        def actualRuleId = rule.getId()
        assert actualRuleId != null: "Rule ID should be generated by database"
        // associate rule with an event
        createRuleEventRelation(eventId, actualRuleId, 0)
        // Update to ONLINE status (OFFLINE -> TEST -> GRAY -> ONLINE)
        rule = ruleService.getRuleById(actualRuleId)
        ruleToUpdate = Rule.builder()
                .id(rule.getId())
                .name(rule.getName())
                .contentType(rule.getContentType())
                .content(rule.getContent())
                .description(rule.getDescription())
                .ruleStatus(RuleStatusEnum.TEST)
                .build()
        ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)
        rule = ruleService.getRuleById(actualRuleId)
        ruleToUpdate = Rule.builder()
                .id(rule.getId())
                .name(rule.getName())
                .contentType(rule.getContentType())
                .content(rule.getContent())
                .description(rule.getDescription())
                .ruleStatus(RuleStatusEnum.GRAY)
                .build()
        ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)
        rule = ruleService.getRuleById(actualRuleId)
        // Now transition to ONLINE
        ruleToUpdate = Rule.builder()
                .id(rule.getId())
                .name(rule.getName())
                .contentType(rule.getContentType())
                .content(rule.getContent())
                .description(rule.getDescription())
                .ruleStatus(RuleStatusEnum.ONLINE)
                .build()
        ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)
        rule = ruleService.getRuleById(actualRuleId)
        // When transitioning to ONLINE, changeRuleStatusToOnline automatically creates a rule group
        // Get the group ID that was created during the transition
        def groupId = getRuleGroupIdForRuleAndEvent(actualRuleId, eventId)
        assert groupId != null && groupId != 0L: "Rule group should be created during ONLINE transition. RuleId: ${actualRuleId}, EventId: ${eventId}"

        when: "change rule status to invalid status"
        rule = ruleService.getRuleById(actualRuleId)
        ruleToUpdate = Rule.builder()
                .id(rule.getId())
                .name(rule.getName())
                .contentType(rule.getContentType())
                .content(rule.getContent())
                .description(rule.getDescription())
                .ruleStatus(invalidStatus)
                .build()
        ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)

        then: "should throw IllegalArgumentException"
        IllegalArgumentException e = thrown()
        e.message.contains("Invalid status transition from")
        e.message.contains("Allowed transitions from")

        where:
        eventId | ruleId | invalidStatus
        1001    | null   | RuleStatusEnum.TEST
        1001    | null   | RuleStatusEnum.GRAY
    }

    @Unroll
    def "Business Logic 2: Rule changes from ONLINE to OFFLINE - remove from group - ruleId: #ruleId, otherRuleIds: #otherRuleIds"() {
        given: "create a rule group with multiple rules"
        def ruleToUpdate
        // Create first rule
        def rule = createRule("Test Rule", ContentTypeEnum.EXPRESSION, RuleStatusEnum.OFFLINE)
        ruleService.createRule(rule)
        def actualRuleId = rule.getId()
        assert actualRuleId != null: "Rule ID should be generated by database"
        // associate rule with an event
        createRuleEventRelation(eventId, actualRuleId, 0)
        // Update to ONLINE status (OFFLINE -> TEST -> GRAY -> ONLINE)
        rule = ruleService.getRuleById(actualRuleId)
        ruleToUpdate = Rule.builder()
                .id(rule.getId())
                .name(rule.getName())
                .contentType(rule.getContentType())
                .content(rule.getContent())
                .description(rule.getDescription())
                .ruleStatus(RuleStatusEnum.TEST)
                .build()
        ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)
        rule = ruleService.getRuleById(actualRuleId)
        ruleToUpdate = Rule.builder()
                .id(rule.getId())
                .name(rule.getName())
                .contentType(rule.getContentType())
                .content(rule.getContent())
                .description(rule.getDescription())
                .ruleStatus(RuleStatusEnum.GRAY)
                .build()
        ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)
        rule = ruleService.getRuleById(actualRuleId)
        // Now transition to ONLINE
        ruleToUpdate = Rule.builder()
                .id(rule.getId())
                .name(rule.getName())
                .contentType(rule.getContentType())
                .content(rule.getContent())
                .description(rule.getDescription())
                .ruleStatus(RuleStatusEnum.ONLINE)
                .build()
        ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)
        rule = ruleService.getRuleById(actualRuleId)
        // When transitioning to ONLINE, changeRuleStatusToOnline automatically creates a rule group
        // Get the group ID that was created during the transition
        def groupId = getRuleGroupIdForRuleAndEvent(actualRuleId, eventId)
        assert groupId != null && groupId != 0L: "Rule group should be created during ONLINE transition. RuleId: ${actualRuleId}, EventId: ${eventId}"

        // Create other rules in the same group by copying the first rule
        def otherRules = []
        otherRuleIds.each { otherRuleId ->
            def ruleDTO = RuleDTO.builder()
                    .name("Copied Rule ${otherRuleId}")
                    .contentType(ContentTypeEnum.EXPRESSION.getId())
                    .content("amount > 100")
                    .build()
            def copiedRule = ruleGroupService.copyRuleInGroup(actualRuleId, ruleDTO)
            def actualOtherRuleId = copiedRule.getId()
            assert actualOtherRuleId != null: "Copied rule ID should be generated by database"
            otherRules.add(actualOtherRuleId)
        }

        when: "change first rule status to OFFLINE"
        rule = ruleService.getRuleById(actualRuleId)
        ruleToUpdate = Rule.builder()
                .id(rule.getId())
                .name(rule.getName())
                .contentType(rule.getContentType())
                .content(rule.getContent())
                .description(rule.getDescription())
                .ruleStatus(RuleStatusEnum.OFFLINE)
                .build()
        ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)

        then: "rule should be removed from group and event associations deleted"
        // Verify rule is set to OFFLINE
        def updatedRule = ruleService.getRuleById(actualRuleId)
        assert updatedRule != null: "Rule should exist. RuleId: ${actualRuleId}"
        assert updatedRule.getRuleStatus() == RuleStatusEnum.OFFLINE: "Rule should be set to OFFLINE. RuleId: ${actualRuleId}, Current status: ${updatedRule.getRuleStatus()}"

        // Verify rule is removed from group (gre_rel)
        def ruleGroupId = getRuleGroupIdForRuleAndEvent(actualRuleId, eventId)
        assert ruleGroupId == null: "Rule should not be in any group. RuleId: ${actualRuleId}"

        // Verify event-rule relation is deleted
        def eventRuleRelations = executionArrangementMapper.selectList(
                new QueryWrapper<ExecutionArrangementEntity>()
                        .eq("rule_id", actualRuleId)
                        .eq("group_id", 0L)
        )
        assert eventRuleRelations == null || eventRuleRelations.isEmpty(): "Event-rule relations should be deleted. RuleId: ${actualRuleId}"

        // Verify rule group is deleted if empty
        def groupEntity = ruleGroupMapper.selectById(groupId)
        if (otherRules.isEmpty()) {
            assert groupEntity == null: "Rule group entity should be deleted when empty. GroupId: ${groupId}"
        } else {
            // If there are other rules, group should still exist
            assert groupEntity != null: "Rule group entity should still exist if there are other rules. GroupId: ${groupId}"
        }

        where:
        eventId | ruleId | otherRuleIds
        1001    | null   | []
        1001    | null   | [1L]
        1001    | null   | [1L, 2L]
    }

    @Unroll
    def "deleteRuleGroup: should delete rule group and all associations - ruleIds: #ruleIds, eventIds: #eventIds"() {
        given: "create a rule group with rules and event associations"
        def ruleToUpdate
        def actualRuleIds = []

        // Create first rule and transition to ONLINE to create the group
        def firstRule = createRule("Rule ${ruleIds[0]}", ContentTypeEnum.EXPRESSION, RuleStatusEnum.OFFLINE)
        ruleService.createRule(firstRule)
        def firstRuleId = firstRule.getId()
        assert firstRuleId != null: "First rule ID should be generated by database"
        actualRuleIds.add(firstRuleId)

        // Create rule-event associations before transitioning to ONLINE
        // createRuleGroup needs event associations to create rule_group_rule_rel records
        if (eventIds.isEmpty()) {
            // If no eventIds provided, create a default one for testing
            createRuleEventRelation(1001, firstRuleId, 0)
        } else {
            eventIds.eachWithIndex { eventId, index ->
                createRuleEventRelation(eventId, firstRuleId, index + 0)
            }
        }

        // Transition first rule to ONLINE (OFFLINE -> TEST -> GRAY -> ONLINE)
        firstRule = ruleService.getRuleById(firstRuleId)
        ruleToUpdate = Rule.builder()
                .id(firstRule.getId())
                .name(firstRule.getName())
                .contentType(firstRule.getContentType())
                .content(firstRule.getContent())
                .description(firstRule.getDescription())
                .ruleStatus(RuleStatusEnum.TEST)
                .build()
        ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)
        firstRule = ruleService.getRuleById(firstRuleId)
        ruleToUpdate = Rule.builder()
                .id(firstRule.getId())
                .name(firstRule.getName())
                .contentType(firstRule.getContentType())
                .content(firstRule.getContent())
                .description(firstRule.getDescription())
                .ruleStatus(RuleStatusEnum.GRAY)
                .build()
        ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)
        firstRule = ruleService.getRuleById(firstRuleId)
        ruleToUpdate = Rule.builder()
                .id(firstRule.getId())
                .name(firstRule.getName())
                .contentType(firstRule.getContentType())
                .content(firstRule.getContent())
                .description(firstRule.getDescription())
                .ruleStatus(RuleStatusEnum.ONLINE)
                .build()
        ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)

        // Get the groupId from the first rule (created by status change handler)
        firstRule = ruleService.getRuleById(firstRuleId)
        def actualGroupId = getRuleGroupByRule(firstRuleId)
        assert actualGroupId != null && actualGroupId != 0L: "First rule should be in a group. RuleId: ${firstRuleId}"

        // Create other rules and add them to the existing group
        if (ruleIds.size() > 1) {
            for (int i = 1; i < ruleIds.size(); i++) {
                def rule = createRule("Rule ${ruleIds[i]}", ContentTypeEnum.EXPRESSION, RuleStatusEnum.OFFLINE)
                ruleService.createRule(rule)
                def actualRuleId = rule.getId()
                assert actualRuleId != null: "Rule ID should be generated by database"
                actualRuleIds.add(actualRuleId)

                // Create rule-event associations before transitioning to ONLINE
                if (eventIds.isEmpty()) {
                    createRuleEventRelation(1001, actualRuleId, 1)
                } else {
                    eventIds.eachWithIndex { eventId, index ->
                        createRuleEventRelation(eventId, actualRuleId, index + 1)
                    }
                }

                // Transition to ONLINE with groupId set (OFFLINE -> TEST -> GRAY -> ONLINE)
                rule = ruleService.getRuleById(actualRuleId)
                ruleToUpdate = Rule.builder()
                        .id(rule.getId())
                        .name(rule.getName())
                        .contentType(rule.getContentType())
                        .content(rule.getContent())
                        .description(rule.getDescription())
                        .ruleStatus(RuleStatusEnum.TEST)
                        .build()
                ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)
                rule = ruleService.getRuleById(actualRuleId)
                ruleToUpdate = Rule.builder()
                        .id(rule.getId())
                        .name(rule.getName())
                        .contentType(rule.getContentType())
                        .content(rule.getContent())
                        .description(rule.getDescription())
                        .ruleStatus(RuleStatusEnum.GRAY)
                        .build()
                ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)
                rule = ruleService.getRuleById(actualRuleId)
                // Set groupId before transitioning to ONLINE so it gets added to existing group
                ruleToUpdate = Rule.builder()
                        .id(rule.getId())
                        .name(rule.getName())
                        .contentType(rule.getContentType())
                        .content(rule.getContent())
                        .description(rule.getDescription())
                        .ruleStatus(RuleStatusEnum.ONLINE)
                        .build()
                ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)
                // Check if rule created its own group
                def ruleGroupId = getRuleGroupByRule(actualRuleId)
                if (ruleGroupId != null && ruleGroupId != actualGroupId) {
                    // Remove rule from its own group and add to the first rule's group
                    QueryWrapper<ExecutionArrangementEntity> deleteWrapper = new QueryWrapper<>()
                    deleteWrapper.eq("group_id", ruleGroupId)
                            .eq("rule_id", actualRuleId)
                    executionArrangementMapper.delete(deleteWrapper)
                    // Delete the empty group
                    ruleGroupMapper.deleteById(ruleGroupId)
                }
                // According to new design, when a rule transitions to ONLINE, it automatically creates a rule group
                // For testing purposes, we'll manually add the rule to the existing group by creating gre_rel record
                // Get the eventId for the group
                def groupEventRelations = executionArrangementMapper.selectList(
                        new QueryWrapper<ExecutionArrangementEntity>()
                                .eq("group_id", actualGroupId)
                )
                if (groupEventRelations != null && !groupEventRelations.isEmpty()) {
                    def eventId = groupEventRelations[0].eventId
                    // Create gre_rel record to add rule to group
                    def greRelation = new ExecutionArrangementEntity()
                    greRelation.setGroupId(actualGroupId)
                    greRelation.setRuleId(actualRuleId)
                    greRelation.setEventId(eventId)
                    greRelation.setAbRatio(0)
                    greRelation.setExeOrder(0)
                    long currentTime = TimeUtil.getCurrentTime()
                    greRelation.setCt((int) currentTime)
                    greRelation.setUt((int) currentTime)
                    executionArrangementMapper.insert(greRelation)
                }
            }
        }

        // Note: createRuleGroup already copies rule-event associations to group-event associations
        // So we don't need to manually create group-event associations here

        // Remove all rules from the group by transitioning them to OFFLINE
        // When the last rule transitions to OFFLINE, the group is automatically deleted
        when: "remove all rules from group by transitioning to OFFLINE"
        actualRuleIds.each { ruleId ->
            def rule = ruleService.getRuleById(ruleId as Long)
            if (rule != null && rule.getRuleStatus() != RuleStatusEnum.OFFLINE) {
                ruleToUpdate = Rule.builder()
                        .id(rule.getId())
                        .name(rule.getName())
                        .contentType(rule.getContentType())
                        .content(rule.getContent())
                        .description(rule.getDescription())
                        .ruleStatus(RuleStatusEnum.OFFLINE)
                        .build()
                ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)
            }
        }

        then: "rule group should be automatically deleted and all associations cleaned up"
        // Verify rule group entity is deleted (automatically deleted when it becomes empty)
        // After transitioning all rules to OFFLINE, the group should be automatically deleted
        // Check if the group entity still exists in the database
        def groupEntity = ruleGroupMapper.selectById(actualGroupId)
        assert groupEntity == null: "Rule group entity should be deleted when empty. GroupId: ${actualGroupId}"
        // Also verify getRuleGroup returns null
        def deletedGroup = ruleGroupService.getRuleGroup(actualGroupId)
        assert deletedGroup == null: "Rule group should be automatically deleted when empty. GroupId: ${actualGroupId}"

        // Verify rule-group relations are deleted
        def ruleGroupRelations = executionArrangementMapper.selectList(
                new QueryWrapper<ExecutionArrangementEntity>()
                        .eq("group_id", actualGroupId)
        )
        assert ruleGroupRelations == null || ruleGroupRelations.isEmpty(): "Rule-group relations should be deleted. GroupId: ${actualGroupId}"

        // Verify group-event relations are deleted
        def groupEventRelations = executionArrangementMapper.selectList(
                new QueryWrapper<ExecutionArrangementEntity>()
                        .eq("group_id", actualGroupId)
        )
        assert groupEventRelations == null || groupEventRelations.isEmpty(): "Group-event relations should be deleted. GroupId: ${actualGroupId}"

        // Verify all rules are OFFLINE and not in any group
        actualRuleIds.each { ruleId ->
            def rule = ruleService.getRuleById(ruleId as Long)
            assert rule != null: "Rule should exist. RuleId: ${ruleId}"
            assert rule.getRuleStatus() == RuleStatusEnum.OFFLINE: "Rule should be OFFLINE. RuleId: ${ruleId}"
            def ruleGroupId = getRuleGroupByRule(ruleId as Long)
            assert ruleGroupId == null || ruleGroupId == 0L: "Rule should not be in any group. RuleId: ${ruleId}"
        }

        where:
        ruleIds      | eventIds
        [1L]         | []
        [1L]         | [1001]
        [1L, 2L]     | [1001, 1002]
        [1L, 2L, 3L] | [1001]
    }

    @Unroll
    def "Business Logic 3: Empty group should be deleted with event associations - eventIds: #eventIds"() {
        given: "create a group with one rule and event associations"
        def ruleToUpdate
        // First create rule as OFFLINE (new rules are always OFFLINE)
        def rule = createRule("Test Rule", ContentTypeEnum.EXPRESSION, RuleStatusEnum.OFFLINE)
        ruleService.createRule(rule)
        def actualRuleId = rule.getId()
        assert actualRuleId != null: "Rule ID should be generated by database"
        // Then update to ONLINE status (OFFLINE -> TEST -> GRAY -> ONLINE)
        // Follow valid state transition path according to state transition rules:
        // - OFFLINE -> only TEST
        // - TEST -> GRAY or OFFLINE
        // - GRAY -> OFFLINE or ONLINE
        rule = ruleService.getRuleById(actualRuleId)
        assert rule != null: "Rule should exist before transition to TEST"
        assert rule.getRuleStatus() == RuleStatusEnum.OFFLINE: "Rule should be in OFFLINE status. RuleId: ${actualRuleId}, Current status: ${rule.getRuleStatus()}"
        // associate rule with an event
        def eventId = 1001
        createRuleEventRelation(eventId, actualRuleId, 0)
        ruleToUpdate = Rule.builder()
                .id(rule.getId())
                .name(rule.getName())
                .contentType(rule.getContentType())
                .content(rule.getContent())
                .description(rule.getDescription())
                .ruleStatus(RuleStatusEnum.TEST)
                .build()
        ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)
        rule = ruleService.getRuleById(actualRuleId)
        assert rule != null: "Rule should exist before transition to GRAY"
        assert rule.getRuleStatus() == RuleStatusEnum.TEST: "Rule should be in TEST status. RuleId: ${actualRuleId}, Current status: ${rule.getRuleStatus()}"
        ruleToUpdate = Rule.builder()
                .id(rule.getId())
                .name(rule.getName())
                .contentType(rule.getContentType())
                .content(rule.getContent())
                .description(rule.getDescription())
                .ruleStatus(RuleStatusEnum.GRAY)
                .build()
        ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)
        rule = ruleService.getRuleById(actualRuleId)
        assert rule != null: "Rule should exist before transition to ONLINE"
        assert rule.getRuleStatus() == RuleStatusEnum.GRAY: "Rule should be in GRAY status. RuleId: ${actualRuleId}, Current status: ${rule.getRuleStatus()}"
        // Now transition to ONLINE
        ruleToUpdate = Rule.builder()
                .id(rule.getId())
                .name(rule.getName())
                .contentType(rule.getContentType())
                .content(rule.getContent())
                .description(rule.getDescription())
                .ruleStatus(RuleStatusEnum.ONLINE)
                .build()
        ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)
        rule = ruleService.getRuleById(actualRuleId)
        // When transitioning to ONLINE, changeRuleStatusToOnline automatically creates a rule group
        // Get the group ID that was created during the transition
        def groupId = getRuleGroupIdForRuleAndEvent(actualRuleId, eventId)
        assert groupId != null && groupId != 0L: "Rule group should be created during ONLINE transition. RuleId: ${actualRuleId}, EventId: ${eventId}"

        // Create group-event associations (if not already created by createRuleGroup)
        // Note: According to new design, createRuleGroup already creates group-event association
        // So we don't need to create it again
        // Note: According to new design, createRuleGroup already creates group-event association for the eventId used
        // So we don't need to create additional associations here
        // The test logic here is kept for compatibility but should be updated according to new design

        when: "remove the only rule from group"
        // Re-load rule from database to get the latest state before updating
        rule = ruleService.getRuleById(actualRuleId)
        assert rule != null: "Rule should exist before transition to OFFLINE"
        assert rule.getRuleStatus() == RuleStatusEnum.ONLINE: "Rule should be in ONLINE status before transitioning to OFFLINE. RuleId: ${actualRuleId}, Current status: ${rule.getRuleStatus()}"
        assert rule.getRuleStatus().canChangeTo(RuleStatusEnum.OFFLINE): "Transition from ${rule.getRuleStatus()} to OFFLINE is not allowed. RuleId: ${actualRuleId}"
        ruleToUpdate = Rule.builder()
                .id(rule.getId())
                .name(rule.getName())
                .contentType(rule.getContentType())
                .content(rule.getContent())
                .description(rule.getDescription())
                .ruleStatus(RuleStatusEnum.OFFLINE)
                .build()
        ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)

        then: "group and its event associations should be deleted"
        // Verify rule group entity is deleted (deleteRuleGroup is called in changeRuleStatusFromABTest)
        def groupEntity = ruleGroupMapper.selectById(groupId)
        assert groupEntity == null: "Rule group entity should be deleted. GroupId: ${groupId}"

        def remainingRelations = executionArrangementMapper.selectList(
                new QueryWrapper<ExecutionArrangementEntity>()
                        .eq("group_id", groupId)
        )
        remainingRelations.isEmpty()
    }


    // Helper methods
    private static Rule createRule(String name, ContentTypeEnum type, RuleStatusEnum status) {
        def rule = Rule.builder()
                .id(null) // Let database auto-generate ID
                .name(name)
                .contentType(type)
                .ruleStatus(status)
                .content("amount > 100")
                .build()
        return rule
    }

    private void createRuleEventRelation(Integer eventId, Long ruleId, Integer order) {
        def relation = new ExecutionArrangementEntity()
        relation.setEventId(eventId)
        relation.setRuleId(ruleId)
        relation.setGroupId(0L)
        relation.setExeOrder(order)
        long currentTime = (long) (TimeUtil.getCurrentTime())
        relation.setCt((int) currentTime)
        relation.setUt((int) currentTime)
        executionArrangementMapper.insert(relation)
    }

    /**
     * Get rule group ID for a rule by querying gre_rel table
     * Returns the first group ID found for the rule (rules can belong to multiple groups for different events)
     *
     * @param ruleId the rule ID
     * @return the group ID, or null if not found
     */
    private Long getRuleGroupByRule(Long ruleId) {
        QueryWrapper<ExecutionArrangementEntity> queryWrapper = new QueryWrapper<>()
        queryWrapper.eq("rule_id", ruleId)
                .ne("group_id", 0L)  // Only return non-zero group_id (rules in groups)
                .last("LIMIT 1")
        def relation = executionArrangementMapper.selectOne(queryWrapper)
        return relation != null && relation.getGroupId() != null && relation.getGroupId() != 0L ? relation.getGroupId() : null
    }

    /**
     * Create a rule update object for status change
     *
     * @param ruleId the rule ID
     * @param newStatus the new status
     * @return rule update object
     */
    private Rule createRuleUpdateObject(Long ruleId, RuleStatusEnum newStatus) {
        def existingRule = ruleService.getRuleById(ruleId)
        assert existingRule != null: "Rule should exist. RuleId: ${ruleId}"

        return Rule.builder()
                .id(existingRule.getId())
                .name(existingRule.getName())
                .contentType(existingRule.getContentType())
                .content(existingRule.getContent())
                .description(existingRule.getDescription())
                .ruleStatus(newStatus)
                .build()
    }

    /**
     * Get rule group ID for a rule and event combination by querying gre_rel table
     *
     * @param ruleId the rule ID
     * @param eventId the event ID
     * @return the group ID, or null if not found
     */
    private Long getRuleGroupIdForRuleAndEvent(Long ruleId, Integer eventId) {
        QueryWrapper<ExecutionArrangementEntity> queryWrapper = new QueryWrapper<>()
        queryWrapper.eq("rule_id", ruleId)
                .eq("event_id", eventId)
        def relation = executionArrangementMapper.selectOne(queryWrapper)
        return relation != null ? relation.getGroupId() : null
    }
}

