package lab.zhang.rule.rule_engine.service.impl


import com.baomidou.mybatisplus.core.conditions.query.QueryWrapper
import lab.zhang.rule.rule_engine.entity.ExecutionEventRelationEntity
import lab.zhang.rule.rule_engine.entity.RuleGroupRuleRelationEntity
import lab.zhang.rule.rule_engine.enums.ExecutionItemTypeEnum
import lab.zhang.rule.rule_engine.enums.RuleStatusEnum
import lab.zhang.rule.rule_engine.enums.ContentTypeEnum
import lab.zhang.rule.rule_engine.mapper.ExecutionEventRelationMapper
import lab.zhang.rule.rule_engine.mapper.RuleGroupMapper
import lab.zhang.rule.rule_engine.mapper.RuleGroupRuleRelationMapper
import lab.zhang.rule.rule_engine.mapper.RuleMapper
import lab.zhang.rule.rule_engine.model.Rule
import lab.zhang.rule.rule_engine.service.RuleGroupService
import lab.zhang.rule.rule_engine.service.RuleService
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.boot.test.context.SpringBootTest
import org.springframework.test.context.ActiveProfiles
import org.springframework.transaction.annotation.Transactional
import spock.lang.Specification
import spock.lang.Unroll

/**
 * RuleGroupService database integration test
 * Tests business logic with real database operations
 *
 * Prerequisites:
 * 1. MySQL database is running on localhost:3306
 * 2. Database 'rule_engine_test' exists
 * 3. Tables are created (see DATABASE_SCHEMA.md)
 *
 * @author Rongjin Zhang
 */
@SpringBootTest
@ActiveProfiles("test")
@Transactional
class RuleGroupServiceImplDatabaseSpec extends Specification {

    @Autowired
    private RuleGroupService ruleGroupService

    @Autowired
    private RuleService ruleService

    @Autowired
    private RuleMapper ruleMapper

    @Autowired
    private RuleGroupMapper ruleGroupMapper

    @Autowired
    private RuleGroupRuleRelationMapper ruleGroupRuleMapper

    @Autowired
    private ExecutionEventRelationMapper executionEventRelationMapper

    def setup() {
        // Clean up test data before each test
        executionEventRelationMapper.delete(null)
        ruleGroupRuleMapper.delete(null)
        ruleGroupMapper.delete(null)
        ruleMapper.delete(null)
    }

    @Unroll
    def "Business Logic 1: Rule changes from #oldStatus to AB_TEST - create group and copy associations - ruleId: #ruleId, eventIds: #eventIds"() {
        given: "create a rule with event associations"
        // First create rule as OFFLINE (new rules are always OFFLINE)
        // Note: ruleId parameter is ignored, database will auto-generate ID
        def rule = createRule("Test Rule", ContentTypeEnum.EXPRESSION, RuleStatusEnum.OFFLINE)
        ruleService.createRule(rule)
        // Get the actual ID from the created rule (database auto-generated)
        def actualRuleId = rule.getId()
        assert actualRuleId != null : "Rule ID should be generated by database"
        def ruleToUpdate
        
        // Then update rule to oldStatus (if not already OFFLINE)
        // Follow valid state transition path according to state transition rules:
        // - OFFLINE -> only TEST
        // - TEST -> GRAY or OFFLINE
        // - GRAY -> OFFLINE or AB_TEST
        // - AB_TEST -> OFFLINE or FULL
        // - FULL -> OFFLINE or AB_TEST
        if (oldStatus != RuleStatusEnum.OFFLINE) {
            // First transition: OFFLINE -> TEST
            rule = ruleService.getRuleById(actualRuleId)
            assert rule != null : "Rule should exist before transition to TEST. RuleId: ${actualRuleId}"
            assert rule.getRuleStatus() == RuleStatusEnum.OFFLINE : "Rule should be in OFFLINE status. RuleId: ${actualRuleId}, Current status: ${rule.getRuleStatus()}"
            ruleToUpdate = Rule.builder()
                    .id(rule.getId())
                    .name(rule.getName())
                    .contentType(rule.getContentType())
                    .content(rule.getContent())
                    .description(rule.getDescription())
                    .ruleStatus(RuleStatusEnum.TEST)
                    .ruleGroupId(rule.getRuleGroupId())
                    .build()
            ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)
            
            if (oldStatus == RuleStatusEnum.GRAY) {
                // Second transition: TEST -> GRAY (valid transition)
                // Re-load rule from database to get the latest state after TEST transition
                rule = ruleService.getRuleById(actualRuleId)
                assert rule != null : "Rule should exist before transition to GRAY. RuleId: ${actualRuleId}"
                assert rule.getRuleStatus() == RuleStatusEnum.TEST : "Rule should be in TEST status. RuleId: ${actualRuleId}, Current status: ${rule.getRuleStatus()}"
                ruleToUpdate = Rule.builder()
                        .id(rule.getId())
                        .name(rule.getName())
                        .contentType(rule.getContentType())
                        .content(rule.getContent())
                        .description(rule.getDescription())
                        .ruleStatus(RuleStatusEnum.GRAY)
                        .ruleGroupId(rule.getRuleGroupId())
                        .build()
                ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)
            } else if (oldStatus == RuleStatusEnum.FULL) {
                // Second transition: TEST -> GRAY
                // Re-load rule from database to get the latest state after TEST transition
                rule = ruleService.getRuleById(actualRuleId)
                assert rule != null : "Rule should exist before transition to GRAY. RuleId: ${actualRuleId}"
                assert rule.getRuleStatus() == RuleStatusEnum.TEST : "Rule should be in TEST status. RuleId: ${actualRuleId}, Current status: ${rule.getRuleStatus()}"
                ruleToUpdate = Rule.builder()
                        .id(rule.getId())
                        .name(rule.getName())
                        .contentType(rule.getContentType())
                        .content(rule.getContent())
                        .description(rule.getDescription())
                        .ruleStatus(RuleStatusEnum.GRAY)
                        .ruleGroupId(rule.getRuleGroupId())
                        .build()
                ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)
                // Third transition: GRAY -> AB_TEST (valid transition)
                // Re-load rule from database to get the latest state after GRAY transition
                rule = ruleService.getRuleById(actualRuleId)
                assert rule != null : "Rule should exist before transition to AB_TEST. RuleId: ${actualRuleId}"
                assert rule.getRuleStatus() == RuleStatusEnum.GRAY : "Rule should be in GRAY status. RuleId: ${actualRuleId}, Current status: ${rule.getRuleStatus()}"
                ruleToUpdate = Rule.builder()
                        .id(rule.getId())
                        .name(rule.getName())
                        .contentType(rule.getContentType())
                        .content(rule.getContent())
                        .description(rule.getDescription())
                        .ruleStatus(RuleStatusEnum.AB_TEST)
                        .ruleGroupId(rule.getRuleGroupId())
                        .build()
                ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)
                // Fourth transition: AB_TEST -> FULL (valid transition)
                // Re-load rule from database to get the latest state after AB_TEST transition
                rule = ruleService.getRuleById(actualRuleId)
                assert rule != null : "Rule should exist before transition to FULL. RuleId: ${actualRuleId}"
                assert rule.getRuleStatus() == RuleStatusEnum.AB_TEST : "Rule should be in AB_TEST status. RuleId: ${actualRuleId}, Current status: ${rule.getRuleStatus()}"
                ruleToUpdate = Rule.builder()
                        .id(rule.getId())
                        .name(rule.getName())
                        .contentType(rule.getContentType())
                        .content(rule.getContent())
                        .description(rule.getDescription())
                        .ruleStatus(RuleStatusEnum.FULL)
                        .ruleGroupId(rule.getRuleGroupId())
                        .build()
                ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)
            }
        }

        // Verify rule is in the expected oldStatus before creating event associations
        rule = ruleService.getRuleById(actualRuleId)
        assert rule != null : "Rule should exist before creating event associations. RuleId: ${actualRuleId}"
        assert rule.getRuleStatus() == oldStatus : "Rule should be in ${oldStatus} status before creating event associations. RuleId: ${actualRuleId}, Current status: ${rule.getRuleStatus()}"

        // Create rule-event associations
        eventIds.eachWithIndex { eventId, index ->
            createRuleEventRelation(eventId, actualRuleId, index + 1)
        }

        when: "change rule status to AB_TEST"
        // Re-load rule from database to get the latest state before updating
        rule = ruleService.getRuleById(actualRuleId)
        assert rule != null : "Rule should exist in database before status change. RuleId: ${actualRuleId}"
        // Verify rule is in the expected oldStatus before transitioning to AB_TEST
        assert rule.getRuleStatus() == oldStatus : "Rule should be in ${oldStatus} status before transitioning to AB_TEST. RuleId: ${actualRuleId}, Current status: ${rule.getRuleStatus()}"
        // Verify the transition from oldStatus to AB_TEST is allowed
        assert rule.getRuleStatus().canTransitionTo(RuleStatusEnum.AB_TEST) : "Transition from ${rule.getRuleStatus()} to AB_TEST is not allowed. RuleId: ${actualRuleId}"
        // Create a new Rule object with all fields from the loaded rule, but with AB_TEST status
        ruleToUpdate = Rule.builder()
                .id(rule.getId())
                .name(rule.getName())
                .contentType(rule.getContentType())
                .content(rule.getContent())
                .description(rule.getDescription())
                .ruleStatus(RuleStatusEnum.AB_TEST)
                .ruleGroupId(rule.getRuleGroupId())
                .build()
        ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)

        // Re-load rule from database to get the latest ruleGroupId (set by createRuleGroup)
        rule = ruleService.getRuleById(actualRuleId)

        then: "group should be created and rule-event associations copied to group"
        assert rule != null : "Rule should exist in database after status change to AB_TEST. RuleId: ${actualRuleId}"
        rule.getRuleGroupId() != null && rule.getRuleGroupId() != 0L
        def groupId = rule.getRuleGroupId()
        
        // Verify relation exists in database directly
        def relations = ruleGroupRuleMapper.selectList(
                new QueryWrapper<RuleGroupRuleRelationEntity>()
                        .eq("group_id", groupId)
                        .eq("rule_id", actualRuleId)
        )
        assert relations != null && !relations.isEmpty() : "Rule-group relation should exist in database. GroupId: ${groupId}, RuleId: ${actualRuleId}"
        
        def group = ruleGroupService.getRuleGroup(groupId)
        group != null
        group.getRuleIds().contains(actualRuleId)

        // Verify group-event associations were created
        def groupEventRelations = executionEventRelationMapper.selectList(
                new QueryWrapper<ExecutionEventRelationEntity>()
                        .eq("item_type", ExecutionItemTypeEnum.RULE_GROUP.getId())
                        .eq("item_id", group.getId())
        )
        groupEventRelations.size() == eventIds.size()
        groupEventRelations*.eventId.sort() == eventIds.sort()

        where:
        ruleId | oldStatus              | eventIds
        null   | RuleStatusEnum.GRAY    | [1001, 1002]
        null   | RuleStatusEnum.FULL    | [1001]
        null   | RuleStatusEnum.FULL    | [1001, 1002, 1003]
    }

    @Unroll
    def "Business Logic 2: Add rule to existing group - copy group-event associations - groupId: #groupId, ruleId: #ruleId, eventIds: #eventIds"() {
        given: "create an existing group with event associations"
        def ruleToUpdate
        // First create rule as OFFLINE (new rules are always OFFLINE)
        def existingRule = createRule("Existing Rule", ContentTypeEnum.EXPRESSION, RuleStatusEnum.OFFLINE)
        ruleService.createRule(existingRule)
        def existingRuleId = existingRule.getId()
        assert existingRuleId != null : "Existing rule ID should be generated by database"
        // Then update to AB_TEST status (OFFLINE -> TEST -> GRAY -> AB_TEST)
        // Follow valid state transition path according to state transition rules:
        // - OFFLINE -> only TEST
        // - TEST -> GRAY or OFFLINE
        // - GRAY -> OFFLINE or AB_TEST
        existingRule = ruleService.getRuleById(existingRuleId)
        assert existingRule != null : "Existing rule should exist before transition to TEST"
        assert existingRule.getRuleStatus() == RuleStatusEnum.OFFLINE : "Existing rule should be in OFFLINE status. RuleId: ${existingRuleId}, Current status: ${existingRule.getRuleStatus()}"
        ruleToUpdate = Rule.builder()
                .id(existingRule.getId())
                .name(existingRule.getName())
                .contentType(existingRule.getContentType())
                .content(existingRule.getContent())
                .description(existingRule.getDescription())
                .ruleStatus(RuleStatusEnum.TEST)
                .ruleGroupId(existingRule.getRuleGroupId())
                .build()
        ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)
        existingRule = ruleService.getRuleById(existingRuleId)
        assert existingRule != null : "Existing rule should exist before transition to GRAY"
        assert existingRule.getRuleStatus() == RuleStatusEnum.TEST : "Existing rule should be in TEST status. RuleId: ${existingRuleId}, Current status: ${existingRule.getRuleStatus()}"
        ruleToUpdate = Rule.builder()
                .id(existingRule.getId())
                .name(existingRule.getName())
                .contentType(existingRule.getContentType())
                .content(existingRule.getContent())
                .description(existingRule.getDescription())
                .ruleStatus(RuleStatusEnum.GRAY)
                .ruleGroupId(existingRule.getRuleGroupId())
                .build()
        ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)
        existingRule = ruleService.getRuleById(existingRuleId)
        assert existingRule != null : "Existing rule should exist before transition to AB_TEST"
        assert existingRule.getRuleStatus() == RuleStatusEnum.GRAY : "Existing rule should be in GRAY status. RuleId: ${existingRuleId}, Current status: ${existingRule.getRuleStatus()}"
        ruleToUpdate = Rule.builder()
                .id(existingRule.getId())
                .name(existingRule.getName())
                .contentType(existingRule.getContentType())
                .content(existingRule.getContent())
                .description(existingRule.getDescription())
                .ruleStatus(RuleStatusEnum.AB_TEST)
                .ruleGroupId(existingRule.getRuleGroupId())
                .build()
        ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)
        existingRule = ruleService.getRuleById(existingRuleId)
        def group = ruleGroupService.createRuleGroup(existingRule)
        groupId = group.getId()

        // Create group-event associations
        eventIds.eachWithIndex { eventId, index ->
            createGroupEventRelation(eventId, groupId, index + 1)
        }

        and: "create a new rule"
        // First create rule as OFFLINE (new rules are always OFFLINE)
        // Note: ruleId parameter is ignored, database will auto-generate ID
        def newRule = createRule("New Rule", ContentTypeEnum.EXPRESSION, RuleStatusEnum.OFFLINE)
        ruleService.createRule(newRule)
        def newRuleId = newRule.getId()
        assert newRuleId != null : "New rule ID should be generated by database"
        // Update to GRAY status (OFFLINE -> TEST -> GRAY)
        // Follow valid state transition path according to state transition rules:
        // - OFFLINE -> only TEST
        // - TEST -> GRAY or OFFLINE
        newRule = ruleService.getRuleById(newRuleId)
        assert newRule != null : "New rule should exist before transition to TEST"
        assert newRule.getRuleStatus() == RuleStatusEnum.OFFLINE : "New rule should be in OFFLINE status. RuleId: ${newRuleId}, Current status: ${newRule.getRuleStatus()}"
        ruleToUpdate = Rule.builder()
                .id(newRule.getId())
                .name(newRule.getName())
                .contentType(newRule.getContentType())
                .content(newRule.getContent())
                .description(newRule.getDescription())
                .ruleStatus(RuleStatusEnum.TEST)
                .ruleGroupId(newRule.getRuleGroupId())
                .build()
        ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)
        newRule = ruleService.getRuleById(newRuleId)
        assert newRule != null : "New rule should exist before transition to GRAY"
        assert newRule.getRuleStatus() == RuleStatusEnum.TEST : "New rule should be in TEST status. RuleId: ${newRuleId}, Current status: ${newRule.getRuleStatus()}"
        ruleToUpdate = Rule.builder()
                .id(newRule.getId())
                .name(newRule.getName())
                .contentType(newRule.getContentType())
                .content(newRule.getContent())
                .description(newRule.getDescription())
                .ruleStatus(RuleStatusEnum.GRAY)
                .ruleGroupId(groupId) // Set ruleGroupId before converting to AB_TEST
                .build()
        ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)

        when: "add new rule to existing group by converting to AB_TEST"
        // Re-load rule from database to get the latest state before updating
        newRule = ruleService.getRuleById(newRuleId)
        assert newRule != null : "New rule should exist before transition to AB_TEST"
        assert newRule.getRuleStatus() == RuleStatusEnum.GRAY : "New rule should be in GRAY status before transitioning to AB_TEST. RuleId: ${newRuleId}, Current status: ${newRule.getRuleStatus()}"
        assert newRule.getRuleStatus().canTransitionTo(RuleStatusEnum.AB_TEST) : "Transition from ${newRule.getRuleStatus()} to AB_TEST is not allowed. RuleId: ${newRuleId}"
        // Converting to AB_TEST with ruleGroupId set will trigger addRuleToGroup
        ruleToUpdate = Rule.builder()
                .id(newRule.getId())
                .name(newRule.getName())
                .contentType(newRule.getContentType())
                .content(newRule.getContent())
                .description(newRule.getDescription())
                .ruleStatus(RuleStatusEnum.AB_TEST)
                .ruleGroupId(newRule.getRuleGroupId())
                .build()
        ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)

        then: "group-event associations should be copied to rule"
        def ruleEventRelations = executionEventRelationMapper.selectList(
                new QueryWrapper<ExecutionEventRelationEntity>()
                        .eq("item_type", ExecutionItemTypeEnum.RULE.getId())
                        .eq("item_id", newRuleId)
        )
        ruleEventRelations.size() == eventIds.size()
        ruleEventRelations*.eventId.sort() == eventIds.sort()

        where:
        groupId   | ruleId | eventIds
        10000001L | null   | [1001, 1002]
        10000002L | null   | [1001]
        10000003L | null   | [1001, 1002, 1003]
    }

    @Unroll
    def "Business Logic 3: Rule changes from AB_TEST to #newStatus - remove from group - ruleId: #ruleId"() {
        given: "create a rule in AB_TEST status in a group"
        def ruleToUpdate
        // First create rule as OFFLINE (new rules are always OFFLINE)
        // Note: ruleId parameter is ignored, database will auto-generate ID
        def rule = createRule("Test Rule", ContentTypeEnum.EXPRESSION, RuleStatusEnum.OFFLINE)
        ruleService.createRule(rule)
        def actualRuleId = rule.getId()
        assert actualRuleId != null : "Rule ID should be generated by database"
        // Then update to AB_TEST status (OFFLINE -> TEST -> GRAY -> AB_TEST)
        // Follow valid state transition path according to state transition rules:
        // - OFFLINE -> only TEST
        // - TEST -> GRAY or OFFLINE
        // - GRAY -> OFFLINE or AB_TEST
        rule = ruleService.getRuleById(actualRuleId)
        assert rule != null : "Rule should exist before transition to TEST"
        assert rule.getRuleStatus() == RuleStatusEnum.OFFLINE : "Rule should be in OFFLINE status. RuleId: ${actualRuleId}, Current status: ${rule.getRuleStatus()}"
        ruleToUpdate = Rule.builder()
                .id(rule.getId())
                .name(rule.getName())
                .contentType(rule.getContentType())
                .content(rule.getContent())
                .description(rule.getDescription())
                .ruleStatus(RuleStatusEnum.TEST)
                .ruleGroupId(rule.getRuleGroupId())
                .build()
        ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)
        rule = ruleService.getRuleById(actualRuleId)
        assert rule != null : "Rule should exist before transition to GRAY"
        assert rule.getRuleStatus() == RuleStatusEnum.TEST : "Rule should be in TEST status. RuleId: ${actualRuleId}, Current status: ${rule.getRuleStatus()}"
        ruleToUpdate = Rule.builder()
                .id(rule.getId())
                .name(rule.getName())
                .contentType(rule.getContentType())
                .content(rule.getContent())
                .description(rule.getDescription())
                .ruleStatus(RuleStatusEnum.GRAY)
                .ruleGroupId(rule.getRuleGroupId())
                .build()
        ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)
        rule = ruleService.getRuleById(actualRuleId)
        assert rule != null : "Rule should exist before transition to AB_TEST"
        assert rule.getRuleStatus() == RuleStatusEnum.GRAY : "Rule should be in GRAY status. RuleId: ${actualRuleId}, Current status: ${rule.getRuleStatus()}"
        ruleToUpdate = Rule.builder()
                .id(rule.getId())
                .name(rule.getName())
                .contentType(rule.getContentType())
                .content(rule.getContent())
                .description(rule.getDescription())
                .ruleStatus(RuleStatusEnum.AB_TEST)
                .ruleGroupId(rule.getRuleGroupId())
                .build()
        ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)
        rule = ruleService.getRuleById(actualRuleId)
        def group = ruleGroupService.createRuleGroup(rule)
        def groupId = group.getId()

        when: "change rule status to other status"
        // Re-load rule from database to get the latest state before updating
        rule = ruleService.getRuleById(actualRuleId)
        assert rule != null : "Rule should exist in database before status change. RuleId: ${actualRuleId}"
        assert rule.getRuleStatus() == RuleStatusEnum.AB_TEST : "Rule should be in AB_TEST status before transitioning to ${newStatus}. RuleId: ${actualRuleId}, Current status: ${rule.getRuleStatus()}"
        assert rule.getRuleStatus().canTransitionTo(newStatus) : "Transition from ${rule.getRuleStatus()} to ${newStatus} is not allowed. RuleId: ${actualRuleId}"
        // Create a new Rule object with all fields from the loaded rule, but with new status
        ruleToUpdate = Rule.builder()
                .id(rule.getId())
                .name(rule.getName())
                .contentType(rule.getContentType())
                .content(rule.getContent())
                .description(rule.getDescription())
                .ruleStatus(newStatus)
                .ruleGroupId(rule.getRuleGroupId())
                .build()
        ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)
        
        // Re-load rule from database to get the latest ruleGroupId (cleared by removeRuleFromGroup)
        rule = ruleService.getRuleById(actualRuleId)

        then: "rule should be removed from group and group should be deleted"
        assert rule != null : "Rule should exist in database after status change. RuleId: ${actualRuleId}"
        // Verify rule's ruleGroupId is set to 0 (DEFAULT_RULE_GROUP_ID)
        assert rule.getRuleGroupId() == null || rule.getRuleGroupId() == 0L : "Rule's ruleGroupId should be null or 0 after removal from group. RuleId: ${actualRuleId}, ruleGroupId: ${rule.getRuleGroupId()}"
        
        // Verify rule group is deleted (doDeleteRuleGroup is called in changeRuleStatusFromABTest)
        def updatedGroup = ruleGroupService.getRuleGroup(groupId)
        assert updatedGroup == null || updatedGroup.getId() == 0L : "Rule group should be deleted after rule status change from AB_TEST. GroupId: ${groupId}"
        
        // Verify rule-group relations are deleted
        def ruleGroupRelations = ruleGroupRuleMapper.selectList(
                new QueryWrapper<RuleGroupRuleRelationEntity>()
                        .eq("group_id", groupId)
        )
        assert ruleGroupRelations == null || ruleGroupRelations.isEmpty() : "Rule-group relations should be deleted. GroupId: ${groupId}"
        
        // Verify group-event relations are deleted
        def groupEventRelations = executionEventRelationMapper.selectList(
                new QueryWrapper<ExecutionEventRelationEntity>()
                        .eq("item_type", ExecutionItemTypeEnum.RULE_GROUP.getId())
                        .eq("item_id", groupId)
        )
        assert groupEventRelations == null || groupEventRelations.isEmpty() : "Group-event relations should be deleted. GroupId: ${groupId}"

        where:
        ruleId | newStatus
        null   | RuleStatusEnum.OFFLINE
        null   | RuleStatusEnum.FULL
    }

    @Unroll
    def "Business Logic 3: Rule changes from AB_TEST to #invalidStatus should throw exception - ruleId: #ruleId"() {
        given: "create a rule in AB_TEST status in a group"
        def ruleToUpdate
        // First create rule as OFFLINE (new rules are always OFFLINE)
        def rule = createRule("Test Rule", ContentTypeEnum.EXPRESSION, RuleStatusEnum.OFFLINE)
        ruleService.createRule(rule)
        def actualRuleId = rule.getId()
        assert actualRuleId != null : "Rule ID should be generated by database"
        // Update to AB_TEST status (OFFLINE -> TEST -> GRAY -> AB_TEST)
        rule = ruleService.getRuleById(actualRuleId)
        ruleToUpdate = Rule.builder()
                .id(rule.getId())
                .name(rule.getName())
                .contentType(rule.getContentType())
                .content(rule.getContent())
                .description(rule.getDescription())
                .ruleStatus(RuleStatusEnum.TEST)
                .ruleGroupId(rule.getRuleGroupId())
                .build()
        ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)
        rule = ruleService.getRuleById(actualRuleId)
        ruleToUpdate = Rule.builder()
                .id(rule.getId())
                .name(rule.getName())
                .contentType(rule.getContentType())
                .content(rule.getContent())
                .description(rule.getDescription())
                .ruleStatus(RuleStatusEnum.GRAY)
                .ruleGroupId(rule.getRuleGroupId())
                .build()
        ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)
        rule = ruleService.getRuleById(actualRuleId)
        ruleToUpdate = Rule.builder()
                .id(rule.getId())
                .name(rule.getName())
                .contentType(rule.getContentType())
                .content(rule.getContent())
                .description(rule.getDescription())
                .ruleStatus(RuleStatusEnum.AB_TEST)
                .ruleGroupId(rule.getRuleGroupId())
                .build()
        ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)
        rule = ruleService.getRuleById(actualRuleId)
        def group = ruleGroupService.createRuleGroup(rule)
        def groupId = group.getId()

        when: "change rule status to invalid status"
        rule = ruleService.getRuleById(actualRuleId)
        ruleToUpdate = Rule.builder()
                .id(rule.getId())
                .name(rule.getName())
                .contentType(rule.getContentType())
                .content(rule.getContent())
                .description(rule.getDescription())
                .ruleStatus(invalidStatus)
                .ruleGroupId(rule.getRuleGroupId())
                .build()
        ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)

        then: "should throw IllegalArgumentException"
        IllegalArgumentException e = thrown()
        e.message.contains("Invalid status transition from")
        e.message.contains("Allowed transitions from")

        where:
        ruleId | invalidStatus
        null   | RuleStatusEnum.TEST
        null   | RuleStatusEnum.GRAY
    }

    @Unroll
    def "Business Logic 3: Rule changes from AB_TEST to FULL - other rules in group should be set to OFFLINE - ruleId: #ruleId, otherRuleIds: #otherRuleIds"() {
        given: "create a rule group with multiple rules"
        def ruleToUpdate
        // Create first rule
        def rule = createRule("Test Rule", ContentTypeEnum.EXPRESSION, RuleStatusEnum.OFFLINE)
        ruleService.createRule(rule)
        def actualRuleId = rule.getId()
        assert actualRuleId != null : "Rule ID should be generated by database"
        // Update to AB_TEST status (OFFLINE -> TEST -> GRAY -> AB_TEST)
        rule = ruleService.getRuleById(actualRuleId)
        ruleToUpdate = Rule.builder()
                .id(rule.getId())
                .name(rule.getName())
                .contentType(rule.getContentType())
                .content(rule.getContent())
                .description(rule.getDescription())
                .ruleStatus(RuleStatusEnum.TEST)
                .ruleGroupId(rule.getRuleGroupId())
                .build()
        ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)
        rule = ruleService.getRuleById(actualRuleId)
        ruleToUpdate = Rule.builder()
                .id(rule.getId())
                .name(rule.getName())
                .contentType(rule.getContentType())
                .content(rule.getContent())
                .description(rule.getDescription())
                .ruleStatus(RuleStatusEnum.GRAY)
                .ruleGroupId(rule.getRuleGroupId())
                .build()
        ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)
        rule = ruleService.getRuleById(actualRuleId)
        ruleToUpdate = Rule.builder()
                .id(rule.getId())
                .name(rule.getName())
                .contentType(rule.getContentType())
                .content(rule.getContent())
                .description(rule.getDescription())
                .ruleStatus(RuleStatusEnum.AB_TEST)
                .ruleGroupId(rule.getRuleGroupId())
                .build()
        ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)
        rule = ruleService.getRuleById(actualRuleId)
        def group = ruleGroupService.createRuleGroup(rule)
        def groupId = group.getId()

        // Create other rules in the same group
        def otherRules = []
        otherRuleIds.each { otherRuleId ->
            def otherRule = createRule("Other Rule ${otherRuleId}", ContentTypeEnum.EXPRESSION, RuleStatusEnum.OFFLINE)
            ruleService.createRule(otherRule)
            def actualOtherRuleId = otherRule.getId()
            assert actualOtherRuleId != null : "Other rule ID should be generated by database"
            // Update to AB_TEST status
            otherRule = ruleService.getRuleById(actualOtherRuleId)
            ruleToUpdate = Rule.builder()
                    .id(otherRule.getId())
                    .name(otherRule.getName())
                    .contentType(otherRule.getContentType())
                    .content(otherRule.getContent())
                    .description(otherRule.getDescription())
                    .ruleStatus(RuleStatusEnum.TEST)
                    .ruleGroupId(otherRule.getRuleGroupId())
                    .build()
            ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)
            otherRule = ruleService.getRuleById(actualOtherRuleId)
            ruleToUpdate = Rule.builder()
                    .id(otherRule.getId())
                    .name(otherRule.getName())
                    .contentType(otherRule.getContentType())
                    .content(otherRule.getContent())
                    .description(otherRule.getDescription())
                    .ruleStatus(RuleStatusEnum.GRAY)
                    .ruleGroupId(otherRule.getRuleGroupId())
                    .build()
            ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)
            otherRule = ruleService.getRuleById(actualOtherRuleId)
            // Set ruleGroupId before transitioning to AB_TEST so it gets added to existing group
            ruleToUpdate = Rule.builder()
                    .id(otherRule.getId())
                    .name(otherRule.getName())
                    .contentType(otherRule.getContentType())
                    .content(otherRule.getContent())
                    .description(otherRule.getDescription())
                    .ruleStatus(RuleStatusEnum.AB_TEST)
                    .ruleGroupId(groupId) // Set to existing groupId before transition
                    .build()
            ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)
            // After updating to AB_TEST, rule should already be in the group (added by handleRuleStatusChange)
            otherRule = ruleService.getRuleById(actualOtherRuleId)
            otherRules.add(actualOtherRuleId)
        }

        when: "change first rule status to FULL"
        rule = ruleService.getRuleById(actualRuleId)
        ruleToUpdate = Rule.builder()
                .id(rule.getId())
                .name(rule.getName())
                .contentType(rule.getContentType())
                .content(rule.getContent())
                .description(rule.getDescription())
                .ruleStatus(RuleStatusEnum.FULL)
                .ruleGroupId(rule.getRuleGroupId())
                .build()
        ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)

        then: "other rules in group should be set to OFFLINE and group should be deleted"
        // Verify other rules are set to OFFLINE
        if (!otherRules.isEmpty()) {
            otherRules.each { otherRuleId ->
                def otherRule = ruleService.getRuleById(otherRuleId)
                assert otherRule != null : "Other rule should exist. RuleId: ${otherRuleId}"
                assert otherRule.getRuleStatus() == RuleStatusEnum.OFFLINE : "Other rule should be set to OFFLINE. RuleId: ${otherRuleId}, Current status: ${otherRule.getRuleStatus()}"
                assert otherRule.getRuleGroupId() == null || otherRule.getRuleGroupId() == 0L : "Other rule's ruleGroupId should be null or 0. RuleId: ${otherRuleId}, ruleGroupId: ${otherRule.getRuleGroupId()}"
            }
        }
        
        // Verify rule group is deleted
        def updatedGroup = ruleGroupService.getRuleGroup(groupId)
        assert updatedGroup == null || updatedGroup.getId() == 0L : "Rule group should be deleted. GroupId: ${groupId}"

        where:
        ruleId | otherRuleIds
        null   | []
        null   | [1L]
        null   | [1L, 2L]
    }

    @Unroll
    def "doDeleteRuleGroup: should delete rule group and all associations - ruleIds: #ruleIds, eventIds: #eventIds"() {
        given: "create a rule group with rules and event associations"
        def ruleToUpdate
        def actualRuleIds = []
        
        // Create first rule and transition to AB_TEST to create the group
        def firstRule = createRule("Rule ${ruleIds[0]}", ContentTypeEnum.EXPRESSION, RuleStatusEnum.OFFLINE)
        ruleService.createRule(firstRule)
        def firstRuleId = firstRule.getId()
        assert firstRuleId != null : "First rule ID should be generated by database"
        actualRuleIds.add(firstRuleId)
        
        // Transition first rule to AB_TEST (OFFLINE -> TEST -> GRAY -> AB_TEST)
        firstRule = ruleService.getRuleById(firstRuleId)
        ruleToUpdate = Rule.builder()
                .id(firstRule.getId())
                .name(firstRule.getName())
                .contentType(firstRule.getContentType())
                .content(firstRule.getContent())
                .description(firstRule.getDescription())
                .ruleStatus(RuleStatusEnum.TEST)
                .ruleGroupId(firstRule.getRuleGroupId())
                .build()
        ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)
        firstRule = ruleService.getRuleById(firstRuleId)
        ruleToUpdate = Rule.builder()
                .id(firstRule.getId())
                .name(firstRule.getName())
                .contentType(firstRule.getContentType())
                .content(firstRule.getContent())
                .description(firstRule.getDescription())
                .ruleStatus(RuleStatusEnum.GRAY)
                .ruleGroupId(firstRule.getRuleGroupId())
                .build()
        ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)
        firstRule = ruleService.getRuleById(firstRuleId)
        ruleToUpdate = Rule.builder()
                .id(firstRule.getId())
                .name(firstRule.getName())
                .contentType(firstRule.getContentType())
                .content(firstRule.getContent())
                .description(firstRule.getDescription())
                .ruleStatus(RuleStatusEnum.AB_TEST)
                .ruleGroupId(firstRule.getRuleGroupId())
                .build()
        ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)
        
        // Get the groupId from the first rule (created by status change handler)
        firstRule = ruleService.getRuleById(firstRuleId)
        def actualGroupId = firstRule.getRuleGroupId()
        assert actualGroupId != null && actualGroupId != 0L : "First rule should be in a group. RuleId: ${firstRuleId}"
        
        // Create other rules and add them to the existing group
        if (ruleIds.size() > 1) {
            for (int i = 1; i < ruleIds.size(); i++) {
                def rule = createRule("Rule ${ruleIds[i]}", ContentTypeEnum.EXPRESSION, RuleStatusEnum.OFFLINE)
                ruleService.createRule(rule)
                def actualRuleId = rule.getId()
                assert actualRuleId != null : "Rule ID should be generated by database"
                actualRuleIds.add(actualRuleId)
                
                // Transition to AB_TEST with groupId set (OFFLINE -> TEST -> GRAY -> AB_TEST)
                rule = ruleService.getRuleById(actualRuleId)
                ruleToUpdate = Rule.builder()
                        .id(rule.getId())
                        .name(rule.getName())
                        .contentType(rule.getContentType())
                        .content(rule.getContent())
                        .description(rule.getDescription())
                        .ruleStatus(RuleStatusEnum.TEST)
                        .ruleGroupId(rule.getRuleGroupId())
                        .build()
                ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)
                rule = ruleService.getRuleById(actualRuleId)
                ruleToUpdate = Rule.builder()
                        .id(rule.getId())
                        .name(rule.getName())
                        .contentType(rule.getContentType())
                        .content(rule.getContent())
                        .description(rule.getDescription())
                        .ruleStatus(RuleStatusEnum.GRAY)
                        .ruleGroupId(rule.getRuleGroupId())
                        .build()
                ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)
                rule = ruleService.getRuleById(actualRuleId)
                // Set groupId before transitioning to AB_TEST so it gets added to existing group
                ruleToUpdate = Rule.builder()
                        .id(rule.getId())
                        .name(rule.getName())
                        .contentType(rule.getContentType())
                        .content(rule.getContent())
                        .description(rule.getDescription())
                        .ruleStatus(RuleStatusEnum.AB_TEST)
                        .ruleGroupId(actualGroupId) // Set to existing groupId before transition
                        .build()
                ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)
            }
        }
        
        // Create group-event associations
        eventIds.eachWithIndex { eventId, index ->
            createGroupEventRelation(eventId, actualGroupId, index + 1)
        }

        when: "delete rule group"
        ruleGroupService.doDeleteRuleGroup(actualGroupId)

        then: "rule group and all associations should be deleted"
        // Verify rule group entity is deleted
        def deletedGroup = ruleGroupService.getRuleGroup(actualGroupId)
        assert deletedGroup == null || deletedGroup.getId() == 0L : "Rule group should be deleted. GroupId: ${actualGroupId}"
        
        // Verify rule-group relations are deleted
        def ruleGroupRelations = ruleGroupRuleMapper.selectList(
                new QueryWrapper<RuleGroupRuleRelationEntity>()
                        .eq("group_id", actualGroupId)
        )
        assert ruleGroupRelations == null || ruleGroupRelations.isEmpty() : "Rule-group relations should be deleted. GroupId: ${actualGroupId}"
        
        // Verify group-event relations are deleted
        def groupEventRelations = executionEventRelationMapper.selectList(
                new QueryWrapper<ExecutionEventRelationEntity>()
                        .eq("item_type", ExecutionItemTypeEnum.RULE_GROUP.getId())
                        .eq("item_id", actualGroupId)
        )
        assert groupEventRelations == null || groupEventRelations.isEmpty() : "Group-event relations should be deleted. GroupId: ${actualGroupId}"

        where:
        ruleIds | eventIds
        [1L]    | []
        [1L]    | [1001]
        [1L, 2L] | [1001, 1002]
        [1L, 2L, 3L] | [1001]
    }

    @Unroll
    def "Business Logic 4: Empty group should be deleted with event associations - eventIds: #eventIds"() {
        given: "create a group with one rule and event associations"
        def ruleToUpdate
        // First create rule as OFFLINE (new rules are always OFFLINE)
        def rule = createRule("Test Rule", ContentTypeEnum.EXPRESSION, RuleStatusEnum.OFFLINE)
        ruleService.createRule(rule)
        def actualRuleId = rule.getId()
        assert actualRuleId != null : "Rule ID should be generated by database"
        // Then update to AB_TEST status (OFFLINE -> TEST -> GRAY -> AB_TEST)
        // Follow valid state transition path according to state transition rules:
        // - OFFLINE -> only TEST
        // - TEST -> GRAY or OFFLINE
        // - GRAY -> OFFLINE or AB_TEST
        rule = ruleService.getRuleById(actualRuleId)
        assert rule != null : "Rule should exist before transition to TEST"
        assert rule.getRuleStatus() == RuleStatusEnum.OFFLINE : "Rule should be in OFFLINE status. RuleId: ${actualRuleId}, Current status: ${rule.getRuleStatus()}"
        ruleToUpdate = Rule.builder()
                .id(rule.getId())
                .name(rule.getName())
                .contentType(rule.getContentType())
                .content(rule.getContent())
                .description(rule.getDescription())
                .ruleStatus(RuleStatusEnum.TEST)
                .ruleGroupId(rule.getRuleGroupId())
                .build()
        ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)
        rule = ruleService.getRuleById(actualRuleId)
        assert rule != null : "Rule should exist before transition to GRAY"
        assert rule.getRuleStatus() == RuleStatusEnum.TEST : "Rule should be in TEST status. RuleId: ${actualRuleId}, Current status: ${rule.getRuleStatus()}"
        ruleToUpdate = Rule.builder()
                .id(rule.getId())
                .name(rule.getName())
                .contentType(rule.getContentType())
                .content(rule.getContent())
                .description(rule.getDescription())
                .ruleStatus(RuleStatusEnum.GRAY)
                .ruleGroupId(rule.getRuleGroupId())
                .build()
        ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)
        rule = ruleService.getRuleById(actualRuleId)
        assert rule != null : "Rule should exist before transition to AB_TEST"
        assert rule.getRuleStatus() == RuleStatusEnum.GRAY : "Rule should be in GRAY status. RuleId: ${actualRuleId}, Current status: ${rule.getRuleStatus()}"
        ruleToUpdate = Rule.builder()
                .id(rule.getId())
                .name(rule.getName())
                .contentType(rule.getContentType())
                .content(rule.getContent())
                .description(rule.getDescription())
                .ruleStatus(RuleStatusEnum.AB_TEST)
                .ruleGroupId(rule.getRuleGroupId())
                .build()
        ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)
        rule = ruleService.getRuleById(actualRuleId)
        def group = ruleGroupService.createRuleGroup(rule)
        def groupId = group.getId()

        // Create group-event associations
        eventIds.eachWithIndex { eventId, index ->
            createGroupEventRelation(eventId, groupId, index + 1)
        }

        when: "remove the only rule from group"
        // Re-load rule from database to get the latest state before updating
        rule = ruleService.getRuleById(actualRuleId)
        assert rule != null : "Rule should exist before transition to OFFLINE"
        assert rule.getRuleStatus() == RuleStatusEnum.AB_TEST : "Rule should be in AB_TEST status before transitioning to OFFLINE. RuleId: ${actualRuleId}, Current status: ${rule.getRuleStatus()}"
        assert rule.getRuleStatus().canTransitionTo(RuleStatusEnum.OFFLINE) : "Transition from ${rule.getRuleStatus()} to OFFLINE is not allowed. RuleId: ${actualRuleId}"
        ruleToUpdate = Rule.builder()
                .id(rule.getId())
                .name(rule.getName())
                .contentType(rule.getContentType())
                .content(rule.getContent())
                .description(rule.getDescription())
                .ruleStatus(RuleStatusEnum.OFFLINE)
                .ruleGroupId(rule.getRuleGroupId())
                .build()
        ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)

        then: "group and its event associations should be deleted"
        def deletedGroup = ruleGroupService.getRuleGroup(groupId)
        // getRuleGroup returns empty RuleGroup (id=0) instead of null when group doesn't exist
        deletedGroup == null || deletedGroup.getId() == 0L

        def remainingRelations = executionEventRelationMapper.selectList(
                new QueryWrapper<ExecutionEventRelationEntity>()
                        .eq("item_type", ExecutionItemTypeEnum.RULE_GROUP.getId())
                        .eq("item_id", groupId)
        )
        remainingRelations.isEmpty()

        where:
        eventIds << [[1001, 1002], [1001], []]
    }

    @Unroll
    def "createRuleGroupWithRules: should validate rule existence in batch - existingRuleIds: #existingRuleIds, nonExistentRuleIds: #nonExistentRuleIds"() {
        given: "create rules in database"
        def ruleToUpdate
        def actualRuleIds = []
        existingRuleIds.each { ruleId ->
            // Note: ruleId parameter is ignored, database will auto-generate ID
            def rule = createRule("Rule $ruleId", ContentTypeEnum.EXPRESSION, RuleStatusEnum.OFFLINE)
            ruleService.createRule(rule)
            def actualRuleId = rule.getId()
            assert actualRuleId != null : "Rule ID should be generated by database"
            actualRuleIds.add(actualRuleId)
            // Update to GRAY status (OFFLINE -> TEST -> GRAY)
            // Follow valid state transition path according to state transition rules:
            // - OFFLINE -> only TEST
            // - TEST -> GRAY or OFFLINE
            // Re-load rule from database before updating
            rule = ruleService.getRuleById(actualRuleId)
            assert rule != null : "Rule should exist before transition to TEST. RuleId: ${actualRuleId}"
            assert rule.getRuleStatus() == RuleStatusEnum.OFFLINE : "Rule should be in OFFLINE status. RuleId: ${actualRuleId}, Current status: ${rule.getRuleStatus()}"
            ruleToUpdate = Rule.builder()
                    .id(rule.getId())
                    .name(rule.getName())
                    .contentType(rule.getContentType())
                    .content(rule.getContent())
                    .description(rule.getDescription())
                    .ruleStatus(RuleStatusEnum.TEST)
                    .ruleGroupId(rule.getRuleGroupId())
                    .build()
            ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)
            // Re-load rule from database before updating to GRAY
            rule = ruleService.getRuleById(actualRuleId)
            assert rule != null : "Rule should exist before transition to GRAY. RuleId: ${actualRuleId}"
            assert rule.getRuleStatus() == RuleStatusEnum.TEST : "Rule should be in TEST status. RuleId: ${actualRuleId}, Current status: ${rule.getRuleStatus()}"
            ruleToUpdate = Rule.builder()
                    .id(rule.getId())
                    .name(rule.getName())
                    .contentType(rule.getContentType())
                    .content(rule.getContent())
                    .description(rule.getDescription())
                    .ruleStatus(RuleStatusEnum.GRAY)
                    .ruleGroupId(rule.getRuleGroupId())
                    .build()
            ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)
        }

        def rules = [:]
        actualRuleIds.each { actualRuleId ->
            rules[actualRuleId] = 50
        }
        nonExistentRuleIds.each { ruleId ->
            rules[ruleId] = 50
        }

        when: "create rule group with rules"
        def group = ruleGroupService.createRuleGroupWithRules(rules)
        
        then: "group should be created successfully"
        group != null
        group.getId() != null
        group.getRuleIds().size() == actualRuleIds.size()

        where:
        existingRuleIds | nonExistentRuleIds
        [1L, 2L, 3L]    | []
    }

    @Unroll
    def "createRuleGroupWithRules: should throw exception when rules do not exist - existingRuleIds: #existingRuleIds, nonExistentRuleIds: #nonExistentRuleIds"() {
        given: "create rules in database"
        def ruleToUpdate
        def actualRuleIds = []
        existingRuleIds.each { ruleId ->
            // Note: ruleId parameter is ignored, database will auto-generate ID
            def rule = createRule("Rule $ruleId", ContentTypeEnum.EXPRESSION, RuleStatusEnum.OFFLINE)
            ruleService.createRule(rule)
            def actualRuleId = rule.getId()
            assert actualRuleId != null : "Rule ID should be generated by database"
            actualRuleIds.add(actualRuleId)
            // Update to GRAY status (OFFLINE -> TEST -> GRAY)
            // Follow valid state transition path according to state transition rules:
            // - OFFLINE -> only TEST
            // - TEST -> GRAY or OFFLINE
            // Re-load rule from database before updating
            rule = ruleService.getRuleById(actualRuleId)
            assert rule != null : "Rule should exist before transition to TEST. RuleId: ${actualRuleId}"
            assert rule.getRuleStatus() == RuleStatusEnum.OFFLINE : "Rule should be in OFFLINE status. RuleId: ${actualRuleId}, Current status: ${rule.getRuleStatus()}"
            ruleToUpdate = Rule.builder()
                    .id(rule.getId())
                    .name(rule.getName())
                    .contentType(rule.getContentType())
                    .content(rule.getContent())
                    .description(rule.getDescription())
                    .ruleStatus(RuleStatusEnum.TEST)
                    .ruleGroupId(rule.getRuleGroupId())
                    .build()
            ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)
            // Re-load rule from database before updating to GRAY
            rule = ruleService.getRuleById(actualRuleId)
            assert rule != null : "Rule should exist before transition to GRAY. RuleId: ${actualRuleId}"
            assert rule.getRuleStatus() == RuleStatusEnum.TEST : "Rule should be in TEST status. RuleId: ${actualRuleId}, Current status: ${rule.getRuleStatus()}"
            ruleToUpdate = Rule.builder()
                    .id(rule.getId())
                    .name(rule.getName())
                    .contentType(rule.getContentType())
                    .content(rule.getContent())
                    .description(rule.getDescription())
                    .ruleStatus(RuleStatusEnum.GRAY)
                    .ruleGroupId(rule.getRuleGroupId())
                    .build()
            ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)
        }

        def rules = [:]
        actualRuleIds.each { actualRuleId ->
            rules[actualRuleId] = 50
        }
        nonExistentRuleIds.each { ruleId ->
            rules[ruleId] = 50
        }

        when: "create rule group with rules"
        def exception = null
        try {
            ruleGroupService.createRuleGroupWithRules(rules)
        } catch (IllegalArgumentException e) {
            exception = e
        }
        
        then: "should throw exception with non-existent rule IDs"
        exception != null
        exception.message.contains("Rule IDs do not exist in database")
        nonExistentRuleIds.each { ruleId ->
            assert exception.message.contains(ruleId.toString())
        }

        where:
        existingRuleIds | nonExistentRuleIds
        [1L, 2L]        | [999L]
        [1L]            | [999L, 1000L]
        []              | [999L, 1000L]
    }

    @Unroll
    def "updateRuleGroupWithRules: should validate rule existence in batch - groupId: #groupId, existingRuleIds: #existingRuleIds, nonExistentRuleIds: #nonExistentRuleIds"() {
        given: "create an existing group with rules"
        def ruleToUpdate
        // Create rules for the group
        def existingRule = createRule("Existing Rule", ContentTypeEnum.EXPRESSION, RuleStatusEnum.OFFLINE)
        ruleService.createRule(existingRule)
        def existingRuleId = existingRule.getId()
        assert existingRuleId != null : "Existing rule ID should be generated by database"
        // Update to AB_TEST status (OFFLINE -> TEST -> GRAY -> AB_TEST)
        // Follow valid state transition path according to state transition rules:
        // - OFFLINE -> only TEST
        // - TEST -> GRAY or OFFLINE
        // - GRAY -> OFFLINE or AB_TEST
        existingRule = ruleService.getRuleById(existingRuleId)
        assert existingRule != null : "Existing rule should exist before transition to TEST"
        assert existingRule.getRuleStatus() == RuleStatusEnum.OFFLINE : "Existing rule should be in OFFLINE status. RuleId: ${existingRuleId}, Current status: ${existingRule.getRuleStatus()}"
        ruleToUpdate = Rule.builder()
                .id(existingRule.getId())
                .name(existingRule.getName())
                .contentType(existingRule.getContentType())
                .content(existingRule.getContent())
                .description(existingRule.getDescription())
                .ruleStatus(RuleStatusEnum.TEST)
                .ruleGroupId(existingRule.getRuleGroupId())
                .build()
        ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)
        existingRule = ruleService.getRuleById(existingRuleId)
        assert existingRule != null : "Existing rule should exist before transition to GRAY"
        assert existingRule.getRuleStatus() == RuleStatusEnum.TEST : "Existing rule should be in TEST status. RuleId: ${existingRuleId}, Current status: ${existingRule.getRuleStatus()}"
        ruleToUpdate = Rule.builder()
                .id(existingRule.getId())
                .name(existingRule.getName())
                .contentType(existingRule.getContentType())
                .content(existingRule.getContent())
                .description(existingRule.getDescription())
                .ruleStatus(RuleStatusEnum.GRAY)
                .ruleGroupId(existingRule.getRuleGroupId())
                .build()
        ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)
        existingRule = ruleService.getRuleById(existingRuleId)
        assert existingRule != null : "Existing rule should exist before transition to AB_TEST"
        assert existingRule.getRuleStatus() == RuleStatusEnum.GRAY : "Existing rule should be in GRAY status. RuleId: ${existingRuleId}, Current status: ${existingRule.getRuleStatus()}"
        ruleToUpdate = Rule.builder()
                .id(existingRule.getId())
                .name(existingRule.getName())
                .contentType(existingRule.getContentType())
                .content(existingRule.getContent())
                .description(existingRule.getDescription())
                .ruleStatus(RuleStatusEnum.AB_TEST)
                .ruleGroupId(existingRule.getRuleGroupId())
                .build()
        ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)
        existingRule = ruleService.getRuleById(existingRuleId)
        def group = ruleGroupService.createRuleGroup(existingRule)
        groupId = group.getId()

        // Create additional rules in database
        def actualRuleIds = []
        existingRuleIds.each { ruleId ->
            // Note: ruleId parameter is ignored, database will auto-generate ID
            def rule = createRule("Rule $ruleId", ContentTypeEnum.EXPRESSION, RuleStatusEnum.OFFLINE)
            ruleService.createRule(rule)
            def actualRuleId = rule.getId()
            assert actualRuleId != null : "Rule ID should be generated by database"
            actualRuleIds.add(actualRuleId)
            // Update to GRAY status (OFFLINE -> TEST -> GRAY)
            // Follow valid state transition path according to state transition rules:
            // - OFFLINE -> only TEST
            // - TEST -> GRAY or OFFLINE
            rule = ruleService.getRuleById(actualRuleId)
            assert rule != null : "Rule should exist before transition to TEST. RuleId: ${actualRuleId}"
            assert rule.getRuleStatus() == RuleStatusEnum.OFFLINE : "Rule should be in OFFLINE status. RuleId: ${actualRuleId}, Current status: ${rule.getRuleStatus()}"
            ruleToUpdate = Rule.builder()
                    .id(rule.getId())
                    .name(rule.getName())
                    .contentType(rule.getContentType())
                    .content(rule.getContent())
                    .description(rule.getDescription())
                    .ruleStatus(RuleStatusEnum.TEST)
                    .ruleGroupId(rule.getRuleGroupId())
                    .build()
            ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)
            rule = ruleService.getRuleById(actualRuleId)
            assert rule != null : "Rule should exist before transition to GRAY. RuleId: ${actualRuleId}"
            assert rule.getRuleStatus() == RuleStatusEnum.TEST : "Rule should be in TEST status. RuleId: ${actualRuleId}, Current status: ${rule.getRuleStatus()}"
            ruleToUpdate = Rule.builder()
                    .id(rule.getId())
                    .name(rule.getName())
                    .contentType(rule.getContentType())
                    .content(rule.getContent())
                    .description(rule.getDescription())
                    .ruleStatus(RuleStatusEnum.GRAY)
                    .ruleGroupId(rule.getRuleGroupId())
                    .build()
            ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)
        }

        def rules = [:]
        actualRuleIds.each { actualRuleId ->
            rules[actualRuleId] = 50
        }
        nonExistentRuleIds.each { ruleId ->
            rules[ruleId] = 50
        }

        when: "update rule group with rules"
        ruleGroupService.updateRuleGroupWithRules(groupId, rules)
        
        then: "group should be updated successfully"
        def updatedGroup = ruleGroupService.getRuleGroup(groupId)
        updatedGroup != null
        updatedGroup.getRuleIds().size() == actualRuleIds.size()

        where:
        groupId   | existingRuleIds | nonExistentRuleIds
        10000001L | [1L, 2L, 3L]    | []
    }

    @Unroll
    def "updateRuleGroupWithRules: should throw exception when rules do not exist - groupId: #groupId, existingRuleIds: #existingRuleIds, nonExistentRuleIds: #nonExistentRuleIds"() {
        given: "create an existing group with rules"
        def ruleToUpdate
        // Create rules for the group
        def existingRule = createRule("Existing Rule", ContentTypeEnum.EXPRESSION, RuleStatusEnum.OFFLINE)
        ruleService.createRule(existingRule)
        def existingRuleId = existingRule.getId()
        assert existingRuleId != null : "Existing rule ID should be generated by database"
        // Update to AB_TEST status (OFFLINE -> TEST -> GRAY -> AB_TEST)
        // Follow valid state transition path according to state transition rules:
        // - OFFLINE -> only TEST
        // - TEST -> GRAY or OFFLINE
        // - GRAY -> OFFLINE or AB_TEST
        existingRule = ruleService.getRuleById(existingRuleId)
        assert existingRule != null : "Existing rule should exist before transition to TEST"
        assert existingRule.getRuleStatus() == RuleStatusEnum.OFFLINE : "Existing rule should be in OFFLINE status. RuleId: ${existingRuleId}, Current status: ${existingRule.getRuleStatus()}"
        ruleToUpdate = Rule.builder()
                .id(existingRule.getId())
                .name(existingRule.getName())
                .contentType(existingRule.getContentType())
                .content(existingRule.getContent())
                .description(existingRule.getDescription())
                .ruleStatus(RuleStatusEnum.TEST)
                .ruleGroupId(existingRule.getRuleGroupId())
                .build()
        ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)
        existingRule = ruleService.getRuleById(existingRuleId)
        assert existingRule != null : "Existing rule should exist before transition to GRAY"
        assert existingRule.getRuleStatus() == RuleStatusEnum.TEST : "Existing rule should be in TEST status. RuleId: ${existingRuleId}, Current status: ${existingRule.getRuleStatus()}"
        ruleToUpdate = Rule.builder()
                .id(existingRule.getId())
                .name(existingRule.getName())
                .contentType(existingRule.getContentType())
                .content(existingRule.getContent())
                .description(existingRule.getDescription())
                .ruleStatus(RuleStatusEnum.GRAY)
                .ruleGroupId(existingRule.getRuleGroupId())
                .build()
        ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)
        existingRule = ruleService.getRuleById(existingRuleId)
        assert existingRule != null : "Existing rule should exist before transition to AB_TEST"
        assert existingRule.getRuleStatus() == RuleStatusEnum.GRAY : "Existing rule should be in GRAY status. RuleId: ${existingRuleId}, Current status: ${existingRule.getRuleStatus()}"
        ruleToUpdate = Rule.builder()
                .id(existingRule.getId())
                .name(existingRule.getName())
                .contentType(existingRule.getContentType())
                .content(existingRule.getContent())
                .description(existingRule.getDescription())
                .ruleStatus(RuleStatusEnum.AB_TEST)
                .ruleGroupId(existingRule.getRuleGroupId())
                .build()
        ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)
        existingRule = ruleService.getRuleById(existingRuleId)
        def group = ruleGroupService.createRuleGroup(existingRule)
        groupId = group.getId()

        // Create additional rules in database
        def actualRuleIds = []
        existingRuleIds.each { ruleId ->
            // Note: ruleId parameter is ignored, database will auto-generate ID
            def rule = createRule("Rule $ruleId", ContentTypeEnum.EXPRESSION, RuleStatusEnum.OFFLINE)
            ruleService.createRule(rule)
            def actualRuleId = rule.getId()
            assert actualRuleId != null : "Rule ID should be generated by database"
            actualRuleIds.add(actualRuleId)
            // Update to GRAY status (OFFLINE -> TEST -> GRAY)
            // Follow valid state transition path according to state transition rules:
            // - OFFLINE -> only TEST
            // - TEST -> GRAY or OFFLINE
            rule = ruleService.getRuleById(actualRuleId)
            assert rule != null : "Rule should exist before transition to TEST. RuleId: ${actualRuleId}"
            assert rule.getRuleStatus() == RuleStatusEnum.OFFLINE : "Rule should be in OFFLINE status. RuleId: ${actualRuleId}, Current status: ${rule.getRuleStatus()}"
            ruleToUpdate = Rule.builder()
                    .id(rule.getId())
                    .name(rule.getName())
                    .contentType(rule.getContentType())
                    .content(rule.getContent())
                    .description(rule.getDescription())
                    .ruleStatus(RuleStatusEnum.TEST)
                    .ruleGroupId(rule.getRuleGroupId())
                    .build()
            ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)
            rule = ruleService.getRuleById(actualRuleId)
            assert rule != null : "Rule should exist before transition to GRAY. RuleId: ${actualRuleId}"
            assert rule.getRuleStatus() == RuleStatusEnum.TEST : "Rule should be in TEST status. RuleId: ${actualRuleId}, Current status: ${rule.getRuleStatus()}"
            ruleToUpdate = Rule.builder()
                    .id(rule.getId())
                    .name(rule.getName())
                    .contentType(rule.getContentType())
                    .content(rule.getContent())
                    .description(rule.getDescription())
                    .ruleStatus(RuleStatusEnum.GRAY)
                    .ruleGroupId(rule.getRuleGroupId())
                    .build()
            ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)
        }

        def rules = [:]
        existingRuleIds.each { ruleId ->
            rules[ruleId] = 50
        }
        nonExistentRuleIds.each { ruleId ->
            rules[ruleId] = 50
        }

        when: "update rule group with rules"
        def exception = null
        try {
            ruleGroupService.updateRuleGroupWithRules(groupId, rules)
        } catch (IllegalArgumentException e) {
            exception = e
        }
        
        then: "should throw exception with non-existent rule IDs"
        exception != null
        exception.message.contains("Rule IDs do not exist in database")
        nonExistentRuleIds.each { ruleId ->
            assert exception.message.contains(ruleId.toString())
        }

        where:
        groupId   | existingRuleIds | nonExistentRuleIds
        10000002L | [1L, 2L]        | [999L]
        10000003L | [1L]            | [999L, 1000L]
        10000004L | []              | [999L, 1000L]
    }

    // Helper methods
    private static Rule createRule(String name, ContentTypeEnum type, RuleStatusEnum status) {
        def rule = Rule.builder()
                .id(null) // Let database auto-generate ID
                .name(name)
                .contentType(type)
                .ruleStatus(status)
                .content("amount > 100")
                .build()
        return rule
    }

    private void createRuleEventRelation(Integer eventId, Long ruleId, Integer order) {
        def relation = new ExecutionEventRelationEntity()
        relation.setEventId(eventId)
        relation.setItemType(ExecutionItemTypeEnum.RULE.getId())
        relation.setItemId(ruleId)
        relation.setExecutionOrder(order)
        long currentTime = (long) (System.currentTimeMillis() / 1000)
        relation.setCt((int) currentTime)
        relation.setUt((int) currentTime)
        executionEventRelationMapper.insert(relation)
    }

    private void createGroupEventRelation(Integer eventId, Long groupId, Integer order) {
        def relation = new ExecutionEventRelationEntity()
        relation.setEventId(eventId)
        relation.setItemType(ExecutionItemTypeEnum.RULE_GROUP.getId())
        relation.setItemId(groupId)
        relation.setExecutionOrder(order)
        long currentTime = (long) (System.currentTimeMillis() / 1000)
        relation.setCt((int) currentTime)
        relation.setUt((int) currentTime)
        executionEventRelationMapper.insert(relation)
    }
}

