package lab.zhang.rule.rule_engine.service.impl


import com.baomidou.mybatisplus.core.conditions.query.QueryWrapper
import lab.zhang.rule.rule_engine.entity.ExecutionArrangementEntity
import lab.zhang.rule.rule_engine.enums.RuleStatusEnum
import lab.zhang.rule.rule_engine.enums.ContentTypeEnum
import lab.zhang.rule.rule_engine.mapper.ExecutionArrangementMapper
import lab.zhang.rule.rule_engine.mapper.RuleGroupMapper
import lab.zhang.rule.rule_engine.mapper.RuleMapper
import lab.zhang.rule.rule_engine.model.Rule
import lab.zhang.rule.rule_engine.service.RuleGroupService
import lab.zhang.rule.rule_engine.service.RuleService
import lab.zhang.rule.rule_engine.util.TimeUtil
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.boot.test.context.SpringBootTest
import org.springframework.test.context.ActiveProfiles
import org.springframework.transaction.annotation.Transactional
import spock.lang.Specification
import spock.lang.Unroll

/**
 * RuleGroupService database integration test
 * Tests business logic with real database operations
 *
 * Prerequisites:
 * 1. MySQL database is running on localhost:3306
 * 2. Database 'rule_engine_test' exists
 * 3. Tables are created (see DATABASE_SCHEMA.md)
 *
 * @author Rongjin Zhang
 */
@SpringBootTest
@ActiveProfiles("test")
@Transactional
class RuleGroupServiceImplDatabaseSpec extends Specification {

    @Autowired
    private RuleGroupService ruleGroupService

    @Autowired
    private RuleService ruleService

    @Autowired
    private RuleMapper ruleMapper

    @Autowired
    private RuleGroupMapper ruleGroupMapper

    @Autowired
    private ExecutionArrangementMapper executionArrangementMapper

    def setup() {
        // Clean up test data before each test
        executionArrangementMapper.delete(null)
        ruleGroupMapper.delete(null)
        ruleMapper.delete(null)
    }

    @Unroll
    def "Business Logic 1: Rule changes from #oldStatus to ONLINE - create group for each event - ruleId: #ruleId, eventIds: #eventIds"() {
        given: "create a rule with event associations"
        // First create rule as OFFLINE (new rules are always OFFLINE)
        // Note: ruleId parameter is ignored, database will auto-generate ID
        def rule = createRule("Test Rule", ContentTypeEnum.EXPRESSION, RuleStatusEnum.OFFLINE)
        ruleService.createRule(rule)
        // Get the actual ID from the created rule (database auto-generated)
        def actualRuleId = rule.getId()
        assert actualRuleId != null : "Rule ID should be generated by database"
        def ruleToUpdate
        
        // Then update rule to oldStatus (if not already OFFLINE)
        // Follow valid state transition path according to state transition rules:
        // - OFFLINE -> only TEST
        // - TEST -> GRAY or OFFLINE
        // - GRAY -> OFFLINE or ONLINE
        // - ONLINE -> OFFLINE
        if (oldStatus != RuleStatusEnum.OFFLINE) {
            // First transition: OFFLINE -> TEST
            rule = ruleService.getRuleById(actualRuleId)
            assert rule != null : "Rule should exist before transition to TEST. RuleId: ${actualRuleId}"
            assert rule.getRuleStatus() == RuleStatusEnum.OFFLINE : "Rule should be in OFFLINE status. RuleId: ${actualRuleId}, Current status: ${rule.getRuleStatus()}"
            ruleToUpdate = Rule.builder()
                    .id(rule.getId())
                    .name(rule.getName())
                    .contentType(rule.getContentType())
                    .content(rule.getContent())
                    .description(rule.getDescription())
                    .ruleStatus(RuleStatusEnum.TEST)
                    .build()
            ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)
            
            if (oldStatus == RuleStatusEnum.GRAY || oldStatus == RuleStatusEnum.ONLINE) {
                // Second transition: TEST -> GRAY (valid transition)
                // Re-load rule from database to get the latest state after TEST transition
                rule = ruleService.getRuleById(actualRuleId)
                assert rule != null : "Rule should exist before transition to GRAY. RuleId: ${actualRuleId}"
                assert rule.getRuleStatus() == RuleStatusEnum.TEST : "Rule should be in TEST status. RuleId: ${actualRuleId}, Current status: ${rule.getRuleStatus()}"
                ruleToUpdate = Rule.builder()
                        .id(rule.getId())
                        .name(rule.getName())
                        .contentType(rule.getContentType())
                        .content(rule.getContent())
                        .description(rule.getDescription())
                        .ruleStatus(RuleStatusEnum.GRAY)
                        .build()
                ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)
            }
        }

        // Verify rule is in the expected status before creating event associations
        // Note: If oldStatus is ONLINE, the rule should be in GRAY status (the prerequisite for ONLINE)
        // because ONLINE requires event associations, which we're about to create
        rule = ruleService.getRuleById(actualRuleId)
        assert rule != null : "Rule should exist before creating event associations. RuleId: ${actualRuleId}"
        def expectedStatusBeforeAssociations = (oldStatus == RuleStatusEnum.ONLINE) ? RuleStatusEnum.GRAY : oldStatus
        assert rule.getRuleStatus() == expectedStatusBeforeAssociations : "Rule should be in ${expectedStatusBeforeAssociations} status before creating event associations. RuleId: ${actualRuleId}, Current status: ${rule.getRuleStatus()}"

        // Create rule-event associations
        eventIds.eachWithIndex { eventId, index ->
            createRuleEventRelation(eventId, actualRuleId, index + 1)
        }

        when: "change rule status to ONLINE"
        // Re-load rule from database to get the latest state before updating
        rule = ruleService.getRuleById(actualRuleId)
        assert rule != null : "Rule should exist in database before status change. RuleId: ${actualRuleId}"
        // Verify rule is in the expected status before transitioning to ONLINE
        // Note: If oldStatus is ONLINE, the rule should be in GRAY status (the prerequisite for ONLINE)
        def expectedStatusBeforeTransition = (oldStatus == RuleStatusEnum.ONLINE) ? RuleStatusEnum.GRAY : oldStatus
        assert rule.getRuleStatus() == expectedStatusBeforeTransition : "Rule should be in ${expectedStatusBeforeTransition} status before transitioning to ONLINE. RuleId: ${actualRuleId}, Current status: ${rule.getRuleStatus()}"
        // Verify the transition to ONLINE is allowed
        assert rule.getRuleStatus().canChangeTo(RuleStatusEnum.ONLINE) : "Transition from ${rule.getRuleStatus()} to ONLINE is not allowed. RuleId: ${actualRuleId}"
        // Create a new Rule object with all fields from the loaded rule, but with ONLINE status
        ruleToUpdate = Rule.builder()
                .id(rule.getId())
                .name(rule.getName())
                .contentType(rule.getContentType())
                .content(rule.getContent())
                .description(rule.getDescription())
                .ruleStatus(RuleStatusEnum.ONLINE)
                .build()
        ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)

        // Re-load rule from database
        rule = ruleService.getRuleById(actualRuleId)

        then: "group should be created for each event and event-rule relations deleted"
        assert rule != null : "Rule should exist in database after status change to ONLINE. RuleId: ${actualRuleId}"
        // Verify a rule group is created for each event
        eventIds.each { eventId ->
            def groupId = getRuleGroupIdForRuleAndEvent(actualRuleId, eventId)
            assert groupId != null && groupId != 0L : "Rule should have a group ID for event ${eventId} after transitioning to ONLINE. RuleId: ${actualRuleId}"
            
            // Verify relation exists in database directly
            def relations = executionArrangementMapper.selectList(
                    new QueryWrapper<ExecutionArrangementEntity>()
                            .eq("group_id", groupId)
                            .eq("rule_id", actualRuleId)
                            .eq("event_id", eventId)
            )
            assert relations != null && !relations.isEmpty() : "Rule-group-event relation should exist in database. GroupId: ${groupId}, RuleId: ${actualRuleId}, EventId: ${eventId}"
            
            def group = ruleGroupService.getRuleGroup(groupId)
            assert group != null : "Rule group should exist. GroupId: ${groupId}"
            assert group.getRuleIds().contains(actualRuleId) : "Rule should be in the group. GroupId: ${groupId}, RuleId: ${actualRuleId}"

            // Verify group-event association was created
            // In the new schema, group-event relations are stored in the x table as rule-group-event relations
            // Query for the specific rule-group-event relation (this verifies the group-event association exists)
            def groupEventRelations = executionArrangementMapper.selectList(
                    new QueryWrapper<ExecutionArrangementEntity>()
                            .eq("group_id", groupId)
                            .eq("event_id", eventId)
                            .eq("rule_id", actualRuleId)
            )
            assert groupEventRelations != null && !groupEventRelations.isEmpty() : "Group-event relation should exist. GroupId: ${groupId}, EventId: ${eventId}, RuleId: ${actualRuleId}"

            // Verify event-rule relation was converted (group_id changed from 0 to groupId)
            // In the new design, the record is updated (group_id changed), not deleted
            def eventRuleRelations = executionArrangementMapper.selectList(
                    new QueryWrapper<ExecutionArrangementEntity>()
                            .eq("event_id", eventId)
                            .eq("rule_id", actualRuleId)
                            .eq("group_id", 0L)
            )
            assert eventRuleRelations == null || eventRuleRelations.isEmpty() : "Event-rule relation with group_id=0 should be deleted/converted. RuleId: ${actualRuleId}, EventId: ${eventId}"
        }

        where:
        ruleId | oldStatus              | eventIds
        null   | RuleStatusEnum.GRAY    | [1001, 1002]
        null   | RuleStatusEnum.ONLINE    | [1001]
        null   | RuleStatusEnum.ONLINE    | [1001, 1002, 1003]
    }

    @Unroll
    def "Business Logic 2: Add rule to existing group - copy group-event associations - groupId: #groupId, ruleId: #ruleId, eventIds: #eventIds"() {
        given: "create an existing group with event associations"
        def ruleToUpdate
        // First create rule as OFFLINE (new rules are always OFFLINE)
        def existingRule = createRule("Existing Rule", ContentTypeEnum.EXPRESSION, RuleStatusEnum.OFFLINE)
        ruleService.createRule(existingRule)
        def existingRuleId = existingRule.getId()
        assert existingRuleId != null : "Existing rule ID should be generated by database"
        // Then update to ONLINE status (OFFLINE -> TEST -> GRAY -> ONLINE)
        // Follow valid state transition path according to state transition rules:
        // - OFFLINE -> only TEST
        // - TEST -> GRAY or OFFLINE
        // - GRAY -> OFFLINE or ONLINE
        existingRule = ruleService.getRuleById(existingRuleId)
        assert existingRule != null : "Existing rule should exist before transition to TEST"
        assert existingRule.getRuleStatus() == RuleStatusEnum.OFFLINE : "Existing rule should be in OFFLINE status. RuleId: ${existingRuleId}, Current status: ${existingRule.getRuleStatus()}"
        ruleToUpdate = Rule.builder()
                .id(existingRule.getId())
                .name(existingRule.getName())
                .contentType(existingRule.getContentType())
                .content(existingRule.getContent())
                .description(existingRule.getDescription())
                .ruleStatus(RuleStatusEnum.TEST)
                .build()
        ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)
        existingRule = ruleService.getRuleById(existingRuleId)
        assert existingRule != null : "Existing rule should exist before transition to GRAY"
        assert existingRule.getRuleStatus() == RuleStatusEnum.TEST : "Existing rule should be in TEST status. RuleId: ${existingRuleId}, Current status: ${existingRule.getRuleStatus()}"
        ruleToUpdate = Rule.builder()
                .id(existingRule.getId())
                .name(existingRule.getName())
                .contentType(existingRule.getContentType())
                .content(existingRule.getContent())
                .description(existingRule.getDescription())
                .ruleStatus(RuleStatusEnum.GRAY)
                .build()
        ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)
        existingRule = ruleService.getRuleById(existingRuleId)
        assert existingRule != null : "Existing rule should exist before transition to ONLINE"
        assert existingRule.getRuleStatus() == RuleStatusEnum.GRAY : "Existing rule should be in GRAY status. RuleId: ${existingRuleId}, Current status: ${existingRule.getRuleStatus()}"
        // Create event associations BEFORE transitioning to ONLINE (required by business logic)
        def eventId = eventIds.isEmpty() ? 1001 : eventIds[0]
        createRuleEventRelation(eventId, existingRuleId, 0)
        // Now transition to ONLINE
        ruleToUpdate = Rule.builder()
                .id(existingRule.getId())
                .name(existingRule.getName())
                .contentType(existingRule.getContentType())
                .content(existingRule.getContent())
                .description(existingRule.getDescription())
                .ruleStatus(RuleStatusEnum.ONLINE)
                .build()
        ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)
        existingRule = ruleService.getRuleById(existingRuleId)
        // When transitioning to ONLINE, changeRuleStatusToOnline automatically creates a rule group
        // Get the group ID that was created during the transition
        groupId = getRuleGroupIdForRuleAndEvent(existingRuleId, eventId)
        assert groupId != null && groupId != 0L : "Rule group should be created during ONLINE transition. RuleId: ${existingRuleId}, EventId: ${eventId}"

        // Note: createRuleGroup already creates group-event association, so we don't need to create it again
        // But if there are multiple eventIds, we need to handle them (though according to new design, a group is associated with one event)

        and: "create a new rule"
        // First create rule as OFFLINE (new rules are always OFFLINE)
        // Note: ruleId parameter is ignored, database will auto-generate ID
        def newRule = createRule("New Rule", ContentTypeEnum.EXPRESSION, RuleStatusEnum.OFFLINE)
        ruleService.createRule(newRule)
        def newRuleId = newRule.getId()
        assert newRuleId != null : "New rule ID should be generated by database"
        // Update to GRAY status (OFFLINE -> TEST -> GRAY)
        // Follow valid state transition path according to state transition rules:
        // - OFFLINE -> only TEST
        // - TEST -> GRAY or OFFLINE
        newRule = ruleService.getRuleById(newRuleId)
        assert newRule != null : "New rule should exist before transition to TEST"
        assert newRule.getRuleStatus() == RuleStatusEnum.OFFLINE : "New rule should be in OFFLINE status. RuleId: ${newRuleId}, Current status: ${newRule.getRuleStatus()}"
        ruleToUpdate = Rule.builder()
                .id(newRule.getId())
                .name(newRule.getName())
                .contentType(newRule.getContentType())
                .content(newRule.getContent())
                .description(newRule.getDescription())
                .ruleStatus(RuleStatusEnum.TEST)
                .build()
        ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)
        newRule = ruleService.getRuleById(newRuleId)
        assert newRule != null : "New rule should exist before transition to GRAY"
        assert newRule.getRuleStatus() == RuleStatusEnum.TEST : "New rule should be in TEST status. RuleId: ${newRuleId}, Current status: ${newRule.getRuleStatus()}"
        ruleToUpdate = Rule.builder()
                .id(newRule.getId())
                .name(newRule.getName())
                .contentType(newRule.getContentType())
                .content(newRule.getContent())
                .description(newRule.getDescription())
                .ruleStatus(RuleStatusEnum.GRAY)
                    // Note: ruleGroupId is no longer a field in Rule, it's managed through rule_group_rule_rel table
                .build()
        ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)

        when: "add new rule to existing group by converting to ONLINE"
        // Re-load rule from database to get the latest state before updating
        newRule = ruleService.getRuleById(newRuleId)
        assert newRule != null : "New rule should exist before transition to ONLINE"
        assert newRule.getRuleStatus() == RuleStatusEnum.GRAY : "New rule should be in GRAY status before transitioning to ONLINE. RuleId: ${newRuleId}, Current status: ${newRule.getRuleStatus()}"
        assert newRule.getRuleStatus().canChangeTo(RuleStatusEnum.ONLINE) : "Transition from ${newRule.getRuleStatus()} to ONLINE is not allowed. RuleId: ${newRuleId}"
        // Create event associations BEFORE transitioning to ONLINE (required by business logic)
        // Use the same eventId as the existing group
        createRuleEventRelation(eventId, newRuleId, 0)
        // Converting to ONLINE will create a new group, so we need to remove it and add to existing group
        ruleToUpdate = Rule.builder()
                .id(newRule.getId())
                .name(newRule.getName())
                .contentType(newRule.getContentType())
                .content(newRule.getContent())
                .description(newRule.getDescription())
                .ruleStatus(RuleStatusEnum.ONLINE)
                .build()
        ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)
        // Get the newly created group ID and remove the rule from it
        newRule = ruleService.getRuleById(newRuleId)
        def newRuleGroupId = getRuleGroupIdForRule(newRuleId)
        if (newRuleGroupId != null && newRuleGroupId != groupId) {
            // Remove rule from its own group
            QueryWrapper<ExecutionArrangementEntity> deleteWrapper = new QueryWrapper<>()
            deleteWrapper.eq("group_id", newRuleGroupId)
                    .eq("rule_id", newRuleId)
            executionArrangementMapper.delete(deleteWrapper)
            // Delete the empty group
            ruleGroupMapper.deleteById(newRuleGroupId)
        }
        // According to new design, when a rule transitions to ONLINE, it automatically creates a rule group
        // For testing purposes, we'll manually add the rule to the existing group by creating gre_rel record
        // But first, we need to get the eventId for the group
        // The group should have at least one record (the existing rule's rule-group-event relation)
        def groupEventRelations = executionArrangementMapper.selectList(
                new QueryWrapper<ExecutionArrangementEntity>()
                        .eq("group_id", groupId)
        )
        // Use the eventId we already have (from the existing rule's relation)
        def groupEventId = eventId
        // If groupEventRelations is not empty, use the eventId from the first relation
        if (groupEventRelations != null && !groupEventRelations.isEmpty()) {
            groupEventId = groupEventRelations[0].eventId
        }
        
        // Create gre_rel record to add rule to group
        def greRelation = new ExecutionArrangementEntity()
        greRelation.setGroupId(groupId)
        greRelation.setRuleId(newRuleId)
        greRelation.setEventId(groupEventId)
        greRelation.setAbRatio(0)
        greRelation.setExeOrder(0)
        long currentTime = TimeUtil.getCurrentTime()
        greRelation.setCt((int) currentTime)
        greRelation.setUt((int) currentTime)
        executionArrangementMapper.insert(greRelation)

        then: "rule should be in the group"
        def ruleGroupId = getRuleGroupIdForRuleAndEvent(newRuleId, groupEventId)
        assert ruleGroupId == groupId : "Rule should be in the group. RuleId: ${newRuleId}, GroupId: ${groupId}"

        where:
        groupId   | ruleId | eventIds
        10000001L | null   | [1001, 1002]
        10000002L | null   | [1001]
        10000003L | null   | [1001, 1002, 1003]
    }

    @Unroll
    def "Business Logic 3: Rule changes from ONLINE to #newStatus - remove from group - ruleId: #ruleId"() {
        given: "create a rule in ONLINE status in a group"
        def ruleToUpdate
        // First create rule as OFFLINE (new rules are always OFFLINE)
        // Note: ruleId parameter is ignored, database will auto-generate ID
        def rule = createRule("Test Rule", ContentTypeEnum.EXPRESSION, RuleStatusEnum.OFFLINE)
        ruleService.createRule(rule)
        def actualRuleId = rule.getId()
        assert actualRuleId != null : "Rule ID should be generated by database"
        // Then update to ONLINE status (OFFLINE -> TEST -> GRAY -> ONLINE)
        // Follow valid state transition path according to state transition rules:
        // - OFFLINE -> only TEST
        // - TEST -> GRAY or OFFLINE
        // - GRAY -> OFFLINE or ONLINE
        rule = ruleService.getRuleById(actualRuleId)
        assert rule != null : "Rule should exist before transition to TEST"
        assert rule.getRuleStatus() == RuleStatusEnum.OFFLINE : "Rule should be in OFFLINE status. RuleId: ${actualRuleId}, Current status: ${rule.getRuleStatus()}"
        ruleToUpdate = Rule.builder()
                .id(rule.getId())
                .name(rule.getName())
                .contentType(rule.getContentType())
                .content(rule.getContent())
                .description(rule.getDescription())
                .ruleStatus(RuleStatusEnum.TEST)
                .build()
        ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)
        rule = ruleService.getRuleById(actualRuleId)
        assert rule != null : "Rule should exist before transition to GRAY"
        assert rule.getRuleStatus() == RuleStatusEnum.TEST : "Rule should be in TEST status. RuleId: ${actualRuleId}, Current status: ${rule.getRuleStatus()}"
        ruleToUpdate = Rule.builder()
                .id(rule.getId())
                .name(rule.getName())
                .contentType(rule.getContentType())
                .content(rule.getContent())
                .description(rule.getDescription())
                .ruleStatus(RuleStatusEnum.GRAY)
                .build()
        ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)
        rule = ruleService.getRuleById(actualRuleId)
        assert rule != null : "Rule should exist before transition to ONLINE"
        assert rule.getRuleStatus() == RuleStatusEnum.GRAY : "Rule should be in GRAY status. RuleId: ${actualRuleId}, Current status: ${rule.getRuleStatus()}"
        // Create event associations BEFORE transitioning to ONLINE (required by business logic)
        def eventId = 1001
        createRuleEventRelation(eventId, actualRuleId, 0)
        // Now transition to ONLINE
        ruleToUpdate = Rule.builder()
                .id(rule.getId())
                .name(rule.getName())
                .contentType(rule.getContentType())
                .content(rule.getContent())
                .description(rule.getDescription())
                .ruleStatus(RuleStatusEnum.ONLINE)
                .build()
        ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)
        rule = ruleService.getRuleById(actualRuleId)
        // When transitioning to ONLINE, changeRuleStatusToOnline automatically creates a rule group
        // Get the group ID that was created during the transition
        def groupId = getRuleGroupIdForRuleAndEvent(actualRuleId, eventId)
        assert groupId != null && groupId != 0L : "Rule group should be created during ONLINE transition. RuleId: ${actualRuleId}, EventId: ${eventId}"

        when: "change rule status to other status"
        // Re-load rule from database to get the latest state before updating
        rule = ruleService.getRuleById(actualRuleId)
        assert rule != null : "Rule should exist in database before status change. RuleId: ${actualRuleId}"
        assert rule.getRuleStatus() == RuleStatusEnum.ONLINE : "Rule should be in ONLINE status before transitioning to ${newStatus}. RuleId: ${actualRuleId}, Current status: ${rule.getRuleStatus()}"
        assert rule.getRuleStatus().canChangeTo(newStatus) : "Transition from ${rule.getRuleStatus()} to ${newStatus} is not allowed. RuleId: ${actualRuleId}"
        // Create a new Rule object with all fields from the loaded rule, but with new status
        ruleToUpdate = Rule.builder()
                .id(rule.getId())
                .name(rule.getName())
                .contentType(rule.getContentType())
                .content(rule.getContent())
                .description(rule.getDescription())
                .ruleStatus(newStatus)
                .build()
        ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)
        
        // Re-load rule from database to get the latest ruleGroupId (cleared by removeRuleFromGroup)
        rule = ruleService.getRuleById(actualRuleId)

        then: "rule should be removed from group and group should be deleted"
        assert rule != null : "Rule should exist in database after status change. RuleId: ${actualRuleId}"
        // Verify rule is no longer in any group
        // After transitioning from ONLINE, the rule should have group_id = 0 or no records
        def allRuleRelations = executionArrangementMapper.selectList(
                new QueryWrapper<ExecutionArrangementEntity>()
                        .eq("rule_id", actualRuleId)
        )
        def ruleRelationsWithGroup = allRuleRelations.findAll { it.groupId != null && it.groupId != 0L }
        assert ruleRelationsWithGroup.isEmpty() : "Rule should not be in any group after removal. RuleId: ${actualRuleId}, Relations with group: ${ruleRelationsWithGroup.collect { "groupId=${it.groupId}, eventId=${it.eventId}" }}"
        def currentGroupId = getRuleGroupIdForRule(actualRuleId)
        assert currentGroupId == null : "Rule should not be in any group after removal. RuleId: ${actualRuleId}"
        
        // Verify rule group entity is deleted (deleteRuleGroup is called in changeRuleStatusFromABTest)
        def groupEntity = ruleGroupMapper.selectById(groupId)
        assert groupEntity == null : "Rule group entity should be deleted after rule status change from ONLINE. GroupId: ${groupId}"
        
        // Verify rule-group relations are deleted
        def ruleGroupRelations = executionArrangementMapper.selectList(
                new QueryWrapper<ExecutionArrangementEntity>()
                        .eq("group_id", groupId)
        )
        assert ruleGroupRelations == null || ruleGroupRelations.isEmpty() : "Rule-group relations should be deleted. GroupId: ${groupId}"
        
        // Verify group-event relations are deleted
        def groupEventRelations = executionArrangementMapper.selectList(
                new QueryWrapper<ExecutionArrangementEntity>()
                        .eq("group_id", groupId)
        )
        assert groupEventRelations == null || groupEventRelations.isEmpty() : "Group-event relations should be deleted. GroupId: ${groupId}"

        where:
        ruleId | newStatus
        null   | RuleStatusEnum.OFFLINE
    }

    @Unroll
    def "Business Logic 3: Rule changes from ONLINE to #invalidStatus should throw exception - ruleId: #ruleId"() {
        given: "create a rule in ONLINE status in a group"
        def ruleToUpdate
        // First create rule as OFFLINE (new rules are always OFFLINE)
        def rule = createRule("Test Rule", ContentTypeEnum.EXPRESSION, RuleStatusEnum.OFFLINE)
        ruleService.createRule(rule)
        def actualRuleId = rule.getId()
        assert actualRuleId != null : "Rule ID should be generated by database"
        // Update to ONLINE status (OFFLINE -> TEST -> GRAY -> ONLINE)
        rule = ruleService.getRuleById(actualRuleId)
        ruleToUpdate = Rule.builder()
                .id(rule.getId())
                .name(rule.getName())
                .contentType(rule.getContentType())
                .content(rule.getContent())
                .description(rule.getDescription())
                .ruleStatus(RuleStatusEnum.TEST)
                .build()
        ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)
        rule = ruleService.getRuleById(actualRuleId)
        ruleToUpdate = Rule.builder()
                .id(rule.getId())
                .name(rule.getName())
                .contentType(rule.getContentType())
                .content(rule.getContent())
                .description(rule.getDescription())
                .ruleStatus(RuleStatusEnum.GRAY)
                .build()
        ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)
        rule = ruleService.getRuleById(actualRuleId)
        // Create event associations BEFORE transitioning to ONLINE (required by business logic)
        def eventId = 1001
        createRuleEventRelation(eventId, actualRuleId, 0)
        // Now transition to ONLINE
        ruleToUpdate = Rule.builder()
                .id(rule.getId())
                .name(rule.getName())
                .contentType(rule.getContentType())
                .content(rule.getContent())
                .description(rule.getDescription())
                .ruleStatus(RuleStatusEnum.ONLINE)
                .build()
        ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)
        rule = ruleService.getRuleById(actualRuleId)
        // When transitioning to ONLINE, changeRuleStatusToOnline automatically creates a rule group
        // Get the group ID that was created during the transition
        def groupId = getRuleGroupIdForRuleAndEvent(actualRuleId, eventId)
        assert groupId != null && groupId != 0L : "Rule group should be created during ONLINE transition. RuleId: ${actualRuleId}, EventId: ${eventId}"

        when: "change rule status to invalid status"
        rule = ruleService.getRuleById(actualRuleId)
        ruleToUpdate = Rule.builder()
                .id(rule.getId())
                .name(rule.getName())
                .contentType(rule.getContentType())
                .content(rule.getContent())
                .description(rule.getDescription())
                .ruleStatus(invalidStatus)
                .build()
        ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)

        then: "should throw IllegalArgumentException"
        IllegalArgumentException e = thrown()
        e.message.contains("Invalid status transition from")
        e.message.contains("Allowed transitions from")

        where:
        ruleId | invalidStatus
        null   | RuleStatusEnum.TEST
        null   | RuleStatusEnum.GRAY
    }

    @Unroll
    def "Business Logic 3: Rule changes from ONLINE to OFFLINE - remove from group - ruleId: #ruleId, otherRuleIds: #otherRuleIds"() {
        given: "create a rule group with multiple rules"
        def ruleToUpdate
        // Create first rule
        def rule = createRule("Test Rule", ContentTypeEnum.EXPRESSION, RuleStatusEnum.OFFLINE)
        ruleService.createRule(rule)
        def actualRuleId = rule.getId()
        assert actualRuleId != null : "Rule ID should be generated by database"
        // Update to ONLINE status (OFFLINE -> TEST -> GRAY -> ONLINE)
        rule = ruleService.getRuleById(actualRuleId)
        ruleToUpdate = Rule.builder()
                .id(rule.getId())
                .name(rule.getName())
                .contentType(rule.getContentType())
                .content(rule.getContent())
                .description(rule.getDescription())
                .ruleStatus(RuleStatusEnum.TEST)
                .build()
        ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)
        rule = ruleService.getRuleById(actualRuleId)
        ruleToUpdate = Rule.builder()
                .id(rule.getId())
                .name(rule.getName())
                .contentType(rule.getContentType())
                .content(rule.getContent())
                .description(rule.getDescription())
                .ruleStatus(RuleStatusEnum.GRAY)
                .build()
        ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)
        rule = ruleService.getRuleById(actualRuleId)
        // Create event associations BEFORE transitioning to ONLINE (required by business logic)
        def eventId = 1001
        createRuleEventRelation(eventId, actualRuleId, 0)
        // Now transition to ONLINE
        ruleToUpdate = Rule.builder()
                .id(rule.getId())
                .name(rule.getName())
                .contentType(rule.getContentType())
                .content(rule.getContent())
                .description(rule.getDescription())
                .ruleStatus(RuleStatusEnum.ONLINE)
                .build()
        ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)
        rule = ruleService.getRuleById(actualRuleId)
        // When transitioning to ONLINE, changeRuleStatusToOnline automatically creates a rule group
        // Get the group ID that was created during the transition
        def groupId = getRuleGroupIdForRuleAndEvent(actualRuleId, eventId)
        assert groupId != null && groupId != 0L : "Rule group should be created during ONLINE transition. RuleId: ${actualRuleId}, EventId: ${eventId}"

        // Create other rules in the same group
        def otherRules = []
        otherRuleIds.each { otherRuleId ->
            def otherRule = createRule("Other Rule ${otherRuleId}", ContentTypeEnum.EXPRESSION, RuleStatusEnum.OFFLINE)
            ruleService.createRule(otherRule)
            def actualOtherRuleId = otherRule.getId()
            assert actualOtherRuleId != null : "Other rule ID should be generated by database"
            // Update to ONLINE status
            otherRule = ruleService.getRuleById(actualOtherRuleId)
            ruleToUpdate = Rule.builder()
                    .id(otherRule.getId())
                    .name(otherRule.getName())
                    .contentType(otherRule.getContentType())
                    .content(otherRule.getContent())
                    .description(otherRule.getDescription())
                    .ruleStatus(RuleStatusEnum.TEST)
                    .build()
            ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)
            otherRule = ruleService.getRuleById(actualOtherRuleId)
            ruleToUpdate = Rule.builder()
                    .id(otherRule.getId())
                    .name(otherRule.getName())
                    .contentType(otherRule.getContentType())
                    .content(otherRule.getContent())
                    .description(otherRule.getDescription())
                    .ruleStatus(RuleStatusEnum.GRAY)
                    .build()
            ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)
            otherRule = ruleService.getRuleById(actualOtherRuleId)
            // Create rule-event associations before transitioning to ONLINE
            def otherRuleRelations = executionArrangementMapper.selectList(
                    new QueryWrapper<ExecutionArrangementEntity>()
                            .eq("rule_id", actualOtherRuleId)
                            .eq("group_id", 0L)
            )
            if (otherRuleRelations == null || otherRuleRelations.isEmpty()) {
                createRuleEventRelation(1001, actualOtherRuleId, 1)
            }
            // Transition to ONLINE
            ruleToUpdate = Rule.builder()
                    .id(otherRule.getId())
                    .name(otherRule.getName())
                    .contentType(otherRule.getContentType())
                    .content(otherRule.getContent())
                    .description(otherRule.getDescription())
                    .ruleStatus(RuleStatusEnum.ONLINE)
                    .build()
            ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)
            // Check if rule created its own group
            def otherRuleGroupId = getRuleGroupIdForRule(actualOtherRuleId)
            if (otherRuleGroupId != null && otherRuleGroupId != groupId) {
                // Remove rule from its own group and add to the first rule's group
                QueryWrapper<ExecutionArrangementEntity> deleteWrapper = new QueryWrapper<>()
                deleteWrapper.eq("group_id", otherRuleGroupId)
                        .eq("rule_id", actualOtherRuleId)
                executionArrangementMapper.delete(deleteWrapper)
                // Delete the empty group
                ruleGroupMapper.deleteById(otherRuleGroupId)
            }
            // According to new design, when a rule transitions to ONLINE, it automatically creates a rule group
            // If we want multiple rules in the same group, we need to directly create gre_rel records
            // For testing purposes, we'll create gre_rel records directly
            def greRelation = new ExecutionArrangementEntity()
            greRelation.setGroupId(groupId)
            greRelation.setRuleId(actualOtherRuleId)
            greRelation.setEventId(eventId)
            greRelation.setAbRatio(0)
            greRelation.setExeOrder(0)
            long currentTime = TimeUtil.getCurrentTime()
            greRelation.setCt((int) currentTime)
            greRelation.setUt((int) currentTime)
            executionArrangementMapper.insert(greRelation)
            otherRules.add(actualOtherRuleId)
        }

        when: "change first rule status to OFFLINE"
        rule = ruleService.getRuleById(actualRuleId)
        ruleToUpdate = Rule.builder()
                .id(rule.getId())
                .name(rule.getName())
                .contentType(rule.getContentType())
                .content(rule.getContent())
                .description(rule.getDescription())
                .ruleStatus(RuleStatusEnum.OFFLINE)
                .build()
        ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)

        then: "rule should be removed from group and event associations deleted"
        // Verify rule is set to OFFLINE
        def updatedRule = ruleService.getRuleById(actualRuleId)
        assert updatedRule != null : "Rule should exist. RuleId: ${actualRuleId}"
        assert updatedRule.getRuleStatus() == RuleStatusEnum.OFFLINE : "Rule should be set to OFFLINE. RuleId: ${actualRuleId}, Current status: ${updatedRule.getRuleStatus()}"
        
        // Verify rule is removed from group (gre_rel)
        def ruleGroupId = getRuleGroupIdForRuleAndEvent(actualRuleId, eventId)
        assert ruleGroupId == null : "Rule should not be in any group. RuleId: ${actualRuleId}"
        
        // Verify event-rule relation is deleted
        def eventRuleRelations = executionArrangementMapper.selectList(
                new QueryWrapper<ExecutionArrangementEntity>()
                        .eq("rule_id", actualRuleId)
                        .eq("group_id", 0L)
        )
        assert eventRuleRelations == null || eventRuleRelations.isEmpty() : "Event-rule relations should be deleted. RuleId: ${actualRuleId}"
        
        // Verify rule group is deleted if empty
        def groupEntity = ruleGroupMapper.selectById(groupId)
        if (otherRules.isEmpty()) {
            assert groupEntity == null : "Rule group entity should be deleted when empty. GroupId: ${groupId}"
        } else {
            // If there are other rules, group should still exist
            assert groupEntity != null : "Rule group entity should still exist if there are other rules. GroupId: ${groupId}"
        }

        where:
        ruleId | otherRuleIds
        null   | []
        null   | [1L]
        null   | [1L, 2L]
    }

    @Unroll
    def "deleteRuleGroup: should delete rule group and all associations - ruleIds: #ruleIds, eventIds: #eventIds"() {
        given: "create a rule group with rules and event associations"
        def ruleToUpdate
        def actualRuleIds = []
        
        // Create first rule and transition to ONLINE to create the group
        def firstRule = createRule("Rule ${ruleIds[0]}", ContentTypeEnum.EXPRESSION, RuleStatusEnum.OFFLINE)
        ruleService.createRule(firstRule)
        def firstRuleId = firstRule.getId()
        assert firstRuleId != null : "First rule ID should be generated by database"
        actualRuleIds.add(firstRuleId)
        
        // Create rule-event associations before transitioning to ONLINE
        // createRuleGroup needs event associations to create rule_group_rule_rel records
        if (eventIds.isEmpty()) {
            // If no eventIds provided, create a default one for testing
            createRuleEventRelation(1001, firstRuleId, 1)
        } else {
            eventIds.eachWithIndex { eventId, index ->
                createRuleEventRelation(eventId, firstRuleId, index + 1)
            }
        }
        
        // Transition first rule to ONLINE (OFFLINE -> TEST -> GRAY -> ONLINE)
        firstRule = ruleService.getRuleById(firstRuleId)
        ruleToUpdate = Rule.builder()
                .id(firstRule.getId())
                .name(firstRule.getName())
                .contentType(firstRule.getContentType())
                .content(firstRule.getContent())
                .description(firstRule.getDescription())
                .ruleStatus(RuleStatusEnum.TEST)
                .build()
        ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)
        firstRule = ruleService.getRuleById(firstRuleId)
        ruleToUpdate = Rule.builder()
                .id(firstRule.getId())
                .name(firstRule.getName())
                .contentType(firstRule.getContentType())
                .content(firstRule.getContent())
                .description(firstRule.getDescription())
                .ruleStatus(RuleStatusEnum.GRAY)
                .build()
        ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)
        firstRule = ruleService.getRuleById(firstRuleId)
        ruleToUpdate = Rule.builder()
                .id(firstRule.getId())
                .name(firstRule.getName())
                .contentType(firstRule.getContentType())
                .content(firstRule.getContent())
                .description(firstRule.getDescription())
                .ruleStatus(RuleStatusEnum.ONLINE)
                .build()
        ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)
        
        // Get the groupId from the first rule (created by status change handler)
        firstRule = ruleService.getRuleById(firstRuleId)
        def actualGroupId = getRuleGroupIdForRule(firstRuleId)
        assert actualGroupId != null && actualGroupId != 0L : "First rule should be in a group. RuleId: ${firstRuleId}"
        
        // Create other rules and add them to the existing group
        if (ruleIds.size() > 1) {
            for (int i = 1; i < ruleIds.size(); i++) {
                def rule = createRule("Rule ${ruleIds[i]}", ContentTypeEnum.EXPRESSION, RuleStatusEnum.OFFLINE)
                ruleService.createRule(rule)
                def actualRuleId = rule.getId()
                assert actualRuleId != null : "Rule ID should be generated by database"
                actualRuleIds.add(actualRuleId)
                
                // Create rule-event associations before transitioning to ONLINE
                if (eventIds.isEmpty()) {
                    createRuleEventRelation(1001, actualRuleId, 1)
                } else {
                    eventIds.eachWithIndex { eventId, index ->
                        createRuleEventRelation(eventId, actualRuleId, index + 1)
                    }
                }
                
                // Transition to ONLINE with groupId set (OFFLINE -> TEST -> GRAY -> ONLINE)
                rule = ruleService.getRuleById(actualRuleId)
                ruleToUpdate = Rule.builder()
                        .id(rule.getId())
                        .name(rule.getName())
                        .contentType(rule.getContentType())
                        .content(rule.getContent())
                        .description(rule.getDescription())
                        .ruleStatus(RuleStatusEnum.TEST)
                        .build()
                ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)
                rule = ruleService.getRuleById(actualRuleId)
                ruleToUpdate = Rule.builder()
                        .id(rule.getId())
                        .name(rule.getName())
                        .contentType(rule.getContentType())
                        .content(rule.getContent())
                        .description(rule.getDescription())
                        .ruleStatus(RuleStatusEnum.GRAY)
                        .build()
                ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)
                rule = ruleService.getRuleById(actualRuleId)
                // Set groupId before transitioning to ONLINE so it gets added to existing group
                ruleToUpdate = Rule.builder()
                        .id(rule.getId())
                        .name(rule.getName())
                        .contentType(rule.getContentType())
                        .content(rule.getContent())
                        .description(rule.getDescription())
                        .ruleStatus(RuleStatusEnum.ONLINE)
                        .build()
                ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)
                // Check if rule created its own group
                def ruleGroupId = getRuleGroupIdForRule(actualRuleId)
                if (ruleGroupId != null && ruleGroupId != actualGroupId) {
                    // Remove rule from its own group and add to the first rule's group
                    QueryWrapper<ExecutionArrangementEntity> deleteWrapper = new QueryWrapper<>()
                    deleteWrapper.eq("group_id", ruleGroupId)
                            .eq("rule_id", actualRuleId)
                    executionArrangementMapper.delete(deleteWrapper)
                    // Delete the empty group
                    ruleGroupMapper.deleteById(ruleGroupId)
                }
                // According to new design, when a rule transitions to ONLINE, it automatically creates a rule group
                // For testing purposes, we'll manually add the rule to the existing group by creating gre_rel record
                // Get the eventId for the group
                def groupEventRelations = executionArrangementMapper.selectList(
                        new QueryWrapper<ExecutionArrangementEntity>()
                                .eq("group_id", actualGroupId)
                )
                if (groupEventRelations != null && !groupEventRelations.isEmpty()) {
                    def eventId = groupEventRelations[0].eventId
                    // Create gre_rel record to add rule to group
                    def greRelation = new ExecutionArrangementEntity()
                    greRelation.setGroupId(actualGroupId)
                    greRelation.setRuleId(actualRuleId)
                    greRelation.setEventId(eventId)
                    greRelation.setAbRatio(0)
        greRelation.setExeOrder(0)
                    long currentTime = TimeUtil.getCurrentTime()
                    greRelation.setCt((int) currentTime)
                    greRelation.setUt((int) currentTime)
                    executionArrangementMapper.insert(greRelation)
                }
            }
        }
        
        // Note: createRuleGroup already copies rule-event associations to group-event associations
        // So we don't need to manually create group-event associations here

        // Remove all rules from the group by transitioning them to OFFLINE
        // When the last rule transitions to OFFLINE, the group is automatically deleted
        when: "remove all rules from group by transitioning to OFFLINE"
        actualRuleIds.each { ruleId ->
            def rule = ruleService.getRuleById(ruleId)
            if (rule != null && rule.getRuleStatus() != RuleStatusEnum.OFFLINE) {
                ruleToUpdate = Rule.builder()
                        .id(rule.getId())
                        .name(rule.getName())
                        .contentType(rule.getContentType())
                        .content(rule.getContent())
                        .description(rule.getDescription())
                        .ruleStatus(RuleStatusEnum.OFFLINE)
                        .build()
                ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)
            }
        }

        then: "rule group should be automatically deleted and all associations cleaned up"
        // Verify rule group entity is deleted (automatically deleted when it becomes empty)
        // After transitioning all rules to OFFLINE, the group should be automatically deleted
        // Check if the group entity still exists in the database
        def groupEntity = ruleGroupMapper.selectById(actualGroupId)
        assert groupEntity == null : "Rule group entity should be deleted when empty. GroupId: ${actualGroupId}"
        // Also verify getRuleGroup returns null
        def deletedGroup = ruleGroupService.getRuleGroup(actualGroupId)
        assert deletedGroup == null : "Rule group should be automatically deleted when empty. GroupId: ${actualGroupId}"
        
        // Verify rule-group relations are deleted
        def ruleGroupRelations = executionArrangementMapper.selectList(
                new QueryWrapper<ExecutionArrangementEntity>()
                        .eq("group_id", actualGroupId)
        )
        assert ruleGroupRelations == null || ruleGroupRelations.isEmpty() : "Rule-group relations should be deleted. GroupId: ${actualGroupId}"
        
        // Verify group-event relations are deleted
        def groupEventRelations = executionArrangementMapper.selectList(
                new QueryWrapper<ExecutionArrangementEntity>()
                        .eq("group_id", actualGroupId)
        )
        assert groupEventRelations == null || groupEventRelations.isEmpty() : "Group-event relations should be deleted. GroupId: ${actualGroupId}"
        
        // Verify all rules are OFFLINE and not in any group
        actualRuleIds.each { ruleId ->
            def rule = ruleService.getRuleById(ruleId)
            assert rule != null : "Rule should exist. RuleId: ${ruleId}"
            assert rule.getRuleStatus() == RuleStatusEnum.OFFLINE : "Rule should be OFFLINE. RuleId: ${ruleId}"
            def ruleGroupId = getRuleGroupIdForRule(ruleId)
            assert ruleGroupId == null || ruleGroupId == 0L : "Rule should not be in any group. RuleId: ${ruleId}"
        }

        where:
        ruleIds | eventIds
        [1L]    | []
        [1L]    | [1001]
        [1L, 2L] | [1001, 1002]
        [1L, 2L, 3L] | [1001]
    }

    @Unroll
    def "Business Logic 4: Empty group should be deleted with event associations - eventIds: #eventIds"() {
        given: "create a group with one rule and event associations"
        def ruleToUpdate
        // First create rule as OFFLINE (new rules are always OFFLINE)
        def rule = createRule("Test Rule", ContentTypeEnum.EXPRESSION, RuleStatusEnum.OFFLINE)
        ruleService.createRule(rule)
        def actualRuleId = rule.getId()
        assert actualRuleId != null : "Rule ID should be generated by database"
        // Then update to ONLINE status (OFFLINE -> TEST -> GRAY -> ONLINE)
        // Follow valid state transition path according to state transition rules:
        // - OFFLINE -> only TEST
        // - TEST -> GRAY or OFFLINE
        // - GRAY -> OFFLINE or ONLINE
        rule = ruleService.getRuleById(actualRuleId)
        assert rule != null : "Rule should exist before transition to TEST"
        assert rule.getRuleStatus() == RuleStatusEnum.OFFLINE : "Rule should be in OFFLINE status. RuleId: ${actualRuleId}, Current status: ${rule.getRuleStatus()}"
        ruleToUpdate = Rule.builder()
                .id(rule.getId())
                .name(rule.getName())
                .contentType(rule.getContentType())
                .content(rule.getContent())
                .description(rule.getDescription())
                .ruleStatus(RuleStatusEnum.TEST)
                .build()
        ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)
        rule = ruleService.getRuleById(actualRuleId)
        assert rule != null : "Rule should exist before transition to GRAY"
        assert rule.getRuleStatus() == RuleStatusEnum.TEST : "Rule should be in TEST status. RuleId: ${actualRuleId}, Current status: ${rule.getRuleStatus()}"
        ruleToUpdate = Rule.builder()
                .id(rule.getId())
                .name(rule.getName())
                .contentType(rule.getContentType())
                .content(rule.getContent())
                .description(rule.getDescription())
                .ruleStatus(RuleStatusEnum.GRAY)
                .build()
        ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)
        rule = ruleService.getRuleById(actualRuleId)
        assert rule != null : "Rule should exist before transition to ONLINE"
        assert rule.getRuleStatus() == RuleStatusEnum.GRAY : "Rule should be in GRAY status. RuleId: ${actualRuleId}, Current status: ${rule.getRuleStatus()}"
        // Create event associations BEFORE transitioning to ONLINE (required by business logic)
        def eventId = 1001
        createRuleEventRelation(eventId, actualRuleId, 0)
        // Now transition to ONLINE
        ruleToUpdate = Rule.builder()
                .id(rule.getId())
                .name(rule.getName())
                .contentType(rule.getContentType())
                .content(rule.getContent())
                .description(rule.getDescription())
                .ruleStatus(RuleStatusEnum.ONLINE)
                .build()
        ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)
        rule = ruleService.getRuleById(actualRuleId)
        // When transitioning to ONLINE, changeRuleStatusToOnline automatically creates a rule group
        // Get the group ID that was created during the transition
        def groupId = getRuleGroupIdForRuleAndEvent(actualRuleId, eventId)
        assert groupId != null && groupId != 0L : "Rule group should be created during ONLINE transition. RuleId: ${actualRuleId}, EventId: ${eventId}"

        // Create group-event associations (if not already created by createRuleGroup)
        // Note: According to new design, createRuleGroup already creates group-event association
        // So we don't need to create it again
        // Note: According to new design, createRuleGroup already creates group-event association for the eventId used
        // So we don't need to create additional associations here
        // The test logic here is kept for compatibility but should be updated according to new design

        when: "remove the only rule from group"
        // Re-load rule from database to get the latest state before updating
        rule = ruleService.getRuleById(actualRuleId)
        assert rule != null : "Rule should exist before transition to OFFLINE"
        assert rule.getRuleStatus() == RuleStatusEnum.ONLINE : "Rule should be in ONLINE status before transitioning to OFFLINE. RuleId: ${actualRuleId}, Current status: ${rule.getRuleStatus()}"
        assert rule.getRuleStatus().canChangeTo(RuleStatusEnum.OFFLINE) : "Transition from ${rule.getRuleStatus()} to OFFLINE is not allowed. RuleId: ${actualRuleId}"
        ruleToUpdate = Rule.builder()
                .id(rule.getId())
                .name(rule.getName())
                .contentType(rule.getContentType())
                .content(rule.getContent())
                .description(rule.getDescription())
                .ruleStatus(RuleStatusEnum.OFFLINE)
                .build()
        ruleService.updateRule(ruleToUpdate.getId(), ruleToUpdate)

        then: "group and its event associations should be deleted"
        // Verify rule group entity is deleted (deleteRuleGroup is called in changeRuleStatusFromABTest)
        def groupEntity = ruleGroupMapper.selectById(groupId)
        assert groupEntity == null : "Rule group entity should be deleted. GroupId: ${groupId}"

        def remainingRelations = executionArrangementMapper.selectList(
                new QueryWrapper<ExecutionArrangementEntity>()
                        .eq("group_id", groupId)
        )
        remainingRelations.isEmpty()

        where:
        eventIds << [[1001, 1002], [1001], []]
    }



    // Helper methods
    private static Rule createRule(String name, ContentTypeEnum type, RuleStatusEnum status) {
        def rule = Rule.builder()
                .id(null) // Let database auto-generate ID
                .name(name)
                .contentType(type)
                .ruleStatus(status)
                .content("amount > 100")
                .build()
        return rule
    }

    private void createRuleEventRelation(Integer eventId, Long ruleId, Integer order) {
        def relation = new ExecutionArrangementEntity()
        relation.setEventId(eventId)
        relation.setRuleId(ruleId)
        relation.setGroupId(0L)
        relation.setExeOrder(order)
        long currentTime = (long) (TimeUtil.getCurrentTime())
        relation.setCt((int) currentTime)
        relation.setUt((int) currentTime)
        executionArrangementMapper.insert(relation)
    }

    /**
     * Get rule group ID for a rule by querying gre_rel table
     * Returns the first group ID found for the rule (rules can belong to multiple groups for different events)
     *
     * @param ruleId the rule ID
     * @return the group ID, or null if not found
     */
    private Long getRuleGroupIdForRule(Long ruleId) {
        QueryWrapper<ExecutionArrangementEntity> queryWrapper = new QueryWrapper<>()
        queryWrapper.eq("rule_id", ruleId)
                .ne("group_id", 0L)  // Only return non-zero group_id (rules in groups)
                .last("LIMIT 1")
        def relation = executionArrangementMapper.selectOne(queryWrapper)
        return relation != null && relation.getGroupId() != null && relation.getGroupId() != 0L ? relation.getGroupId() : null
    }

    /**
     * Get rule group ID for a rule and event combination by querying gre_rel table
     *
     * @param ruleId the rule ID
     * @param eventId the event ID
     * @return the group ID, or null if not found
     */
    private Long getRuleGroupIdForRuleAndEvent(Long ruleId, Integer eventId) {
        QueryWrapper<ExecutionArrangementEntity> queryWrapper = new QueryWrapper<>()
        queryWrapper.eq("rule_id", ruleId)
                .eq("event_id", eventId)
        def relation = executionArrangementMapper.selectOne(queryWrapper)
        return relation != null ? relation.getGroupId() : null
    }
}

