package lab.zhang.rule.rule_engine.controller

import lab.zhang.rule.rule_engine.common.TypedValue
import lab.zhang.rule.rule_engine.enums.ContentTypeEnum
import lab.zhang.rule.rule_engine.enums.ExecutionItemTypeEnum
import lab.zhang.rule.rule_engine.enums.RuleStatusEnum
import lab.zhang.rule.rule_engine.enums.ValueTypeEnum
import lab.zhang.rule.rule_engine.entity.ExecutionEventRelationEntity
import lab.zhang.rule.rule_engine.mapper.EventMapper
import lab.zhang.rule.rule_engine.mapper.ExecutionEventRelationMapper
import lab.zhang.rule.rule_engine.mapper.RuleGroupMapper
import lab.zhang.rule.rule_engine.mapper.RuleGroupRuleRelationMapper
import lab.zhang.rule.rule_engine.mapper.RuleMapper
import lab.zhang.rule.rule_engine.model.Rule
import lab.zhang.rule.rule_engine.pojo.qo.EvalQO
import lab.zhang.rule.rule_engine.service.EventService
import lab.zhang.rule.rule_engine.service.RuleGroupService
import lab.zhang.rule.rule_engine.service.RuleService
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.boot.test.context.SpringBootTest
import org.springframework.http.HttpStatus
import org.springframework.test.context.ActiveProfiles
import org.springframework.transaction.annotation.Transactional
import spock.lang.Specification

/**
 * EvalController integration test
 * Tests the eval interface with real database and execution trace
 *
 * Prerequisites:
 * 1. MySQL database is running on localhost:3306
 * 2. Database 'rule_engine_test' exists
 * 3. Tables are created (see DATABASE_SCHEMA.md)
 *
 * @author Rongjin Zhang
 */
@SpringBootTest
@ActiveProfiles("test")
@Transactional
class EvalControllerIntegrationSpec extends Specification {

    @Autowired
    private EvalController evalController

    @Autowired
    private EventService eventService

    @Autowired
    private RuleService ruleService

    @Autowired
    private RuleGroupService ruleGroupService

    @Autowired
    private EventMapper eventMapper

    @Autowired
    private RuleMapper ruleMapper

    @Autowired
    private RuleGroupMapper ruleGroupMapper

    @Autowired
    private RuleGroupRuleRelationMapper ruleGroupRuleRelationMapper

    @Autowired
    private ExecutionEventRelationMapper executionEventRelationMapper

    // Test data IDs
    private static final Long EVENT_ID_1 = 16000001L
    private static final Long EVENT_ID_2 = 16000002L
    private static final Long EVENT_ID_3 = 16000003L
    private static final Long RULE_GROUP_ID = 16002001L

    // Rule IDs (will be auto-generated by database)
    private Long ruleId1  // OFFLINE
    private Long ruleId2  // TEST
    private Long ruleId3  // GRAY
    private Long ruleId4  // AB_TEST (in group)
    private Long ruleId5  // AB_TEST (in group)
    private Long ruleId6  // FULL

    def setup() {
        // Clean up test data before each test
        executionEventRelationMapper.delete(null)
        ruleGroupRuleRelationMapper.delete(null)
        ruleGroupMapper.delete(null)
        ruleMapper.delete(null)
        eventMapper.delete(null)

        // Setup test data
        setupTestData()
    }

    def "test eval interface - integration test with execution trace"() {
        given: "prepare eval request"
        def evalQO = new EvalQO()
        evalQO.userId = 1000L
        evalQO.eventId = EVENT_ID_2
        evalQO.traceId = 9999L
        evalQO.arguments = [
                "amount": new TypedValue(150.0, ValueTypeEnum.DECIMAL)
        ]

        when: "call eval interface"
        def response = evalController.eval(evalQO)

        then: "should return success response with execution trace"
        response.statusCode == HttpStatus.OK
        response.body != null
        response.body.success == true
        response.body.result != null
        response.body.trace != null
        response.body.trace.steps != null
        response.body.trace.steps.size() > 0

        and: "execution trace should contain execution steps"
        def steps = response.body.trace.steps
        steps.each { step ->
            assert step.itemType != null
            assert step.itemId != null
            // All steps in trace are executed rules
            assert step.result != null || step.errmsg != null
        }

        and: "should have executed rules for event 16000002"
        steps.size() > 0
    }

    def "test eval interface - multiple requests to analyze rule group selection distribution"() {
        given: "prepare multiple eval requests with random amount values"
        def requestCount = 1000
        def ruleSelectionCounts = [:]
        def totalExecutions = 0

        when: "call eval interface multiple times"
        requestCount.times { index ->
            def amount = Math.random() * 500  // Random amount between 0 and 500
            def evalQO = new EvalQO()
            evalQO.userId = 1000L + index  // Different userId for each request
            evalQO.eventId = EVENT_ID_2
            evalQO.traceId = 9999L + index
            evalQO.arguments = [
                    "amount": new TypedValue(amount, ValueTypeEnum.DECIMAL)
            ]

            def response = evalController.eval(evalQO)
            assert response.statusCode == HttpStatus.OK
            assert response.body.success == true

            // Analyze execution trace
            def trace = response.body.trace
            if (trace != null && trace.steps != null) {
                trace.steps.each { step ->
                    if (step.itemType == ExecutionItemTypeEnum.RULE_GROUP) {
                        // All steps in trace are executed rules
                        totalExecutions++
                        def selectedRuleId = step.abTestedRuleId
                        if (selectedRuleId != null) {
                            ruleSelectionCounts[selectedRuleId] = (ruleSelectionCounts[selectedRuleId] ?: 0) + 1
                        }
                    }
                }
            }
        }

        then: "should have execution traces for all requests"
        totalExecutions > 0

        and: "rule group selection should follow probability distribution"
        // Rule group has 2 rules with ratios 10 and 50 (total 60, leaving 40% for no selection)
        // Expected distribution: rule4 ~10%, rule5 ~50%, no selection ~40%
        if (totalExecutions > 0) {
            def rule4Count = ruleSelectionCounts[ruleId4] ?: 0
            def rule5Count = ruleSelectionCounts[ruleId5] ?: 0
            def rule4Percentage = (rule4Count / totalExecutions) * 100
            def rule5Percentage = (rule5Count / totalExecutions) * 100
            def noSelectionPercentage = ((totalExecutions - rule4Count - rule5Count) / totalExecutions) * 100

            println "Rule Group Selection Distribution (${totalExecutions} executions):"
            println "  Rule ${ruleId4} (ratio 10): ${rule4Count} times (${String.format("%.2f", rule4Percentage)}%)"
            println "  Rule ${ruleId5} (ratio 50): ${rule5Count} times (${String.format("%.2f", rule5Percentage)}%)"
            println "  No selection: ${totalExecutions - rule4Count - rule5Count} times (${String.format("%.2f", noSelectionPercentage)}%)"

            // Allow some variance (within 5% of expected)
            rule4Percentage >= 5 && rule4Percentage <= 15  // Expected ~10%
            rule5Percentage >= 45 && rule5Percentage <= 55  // Expected ~50%
            noSelectionPercentage >= 35 && noSelectionPercentage <= 45  // Expected ~40%
        } else {
            // If no executions, it might be because environment doesn't allow AB_TEST rules
            println "Warning: No rule group executions found. This might be due to environment configuration."
            // In GRAY environment, AB_TEST rules should execute, so this should not happen
            assert false : "Expected rule group executions but found none. Check environment configuration."
        }
    }

    def "test eval interface - event with no rules should return null result"() {
        given: "prepare eval request for event with no rules"
        def evalQO = new EvalQO()
        evalQO.userId = 1000L
        evalQO.eventId = EVENT_ID_3
        evalQO.traceId = 9999L
        evalQO.arguments = [
                "amount": new TypedValue(150.0, ValueTypeEnum.DECIMAL)
        ]

        when: "call eval interface"
        def response = evalController.eval(evalQO)

        then: "should return null result"
        response.statusCode == HttpStatus.OK
        response.body != null
        response.body.success == true
        response.body.result != null
        response.body.result.value == null
        response.body.trace != null
        response.body.trace.steps != null
        response.body.trace.steps.isEmpty()
    }

    def "test eval interface - execution trace details"() {
        given: "prepare eval request"
        def evalQO = new EvalQO()
        evalQO.userId = 1000L
        evalQO.eventId = EVENT_ID_2
        evalQO.traceId = 9999L
        evalQO.arguments = [
                "amount": new TypedValue(150.0, ValueTypeEnum.DECIMAL)
        ]

        when: "call eval interface"
        def response = evalController.eval(evalQO)

        then: "execution trace should contain detailed information"
        response.statusCode == HttpStatus.OK
        def trace = response.body.trace
        trace != null
        trace.steps != null

        and: "each step should have proper structure"
        trace.steps.eachWithIndex { step, index ->
            // Execution order is implied by the position in the list (index + 1)
            assert step.itemType != null
            assert step.itemId != null
            // All steps in trace are executed rules
            if (step.itemType == ExecutionItemTypeEnum.RULE) {
                // itemId should be rule ID
            } else if (step.itemType == ExecutionItemTypeEnum.RULE_GROUP) {
                // itemId should be rule group ID
                // If abTestedRuleId is not null, it means a rule was selected from the group
            }
            // Each executed step should have either a result or an error message
            assert step.result != null || step.errmsg != null
        }

        and: "should print execution trace for inspection"
        println "\nExecution Trace:"
        trace.steps.eachWithIndex { step, index ->
            def stepInfo = "Step ${index + 1}: ${step.itemType}"
            if (step.itemType == ExecutionItemTypeEnum.RULE) {
                stepInfo += " (Item ID: ${step.itemId})"
            } else {
                stepInfo += " (Item ID: ${step.itemId}, Selected Rule ID: ${step.abTestedRuleId})"
            }
            if (step.result != null) {
                stepInfo += ", Result: ${step.result}"
            }
            if (step.errmsg != null) {
                stepInfo += ", Error: ${step.errmsg}"
            }
            // Last step is the last executed rule
            if (index == trace.steps.size() - 1) {
                stepInfo += " [LAST EXECUTED]"
            }
            println "  ${stepInfo}"
        }
    }

    // Helper methods
    private void setupTestData() {
        // Create 3 events
        createEvent(EVENT_ID_1, "Event 1")
        createEvent(EVENT_ID_2, "Event 2")
        createEvent(EVENT_ID_3, "Event 3")

        // Create 6 rules with different statuses
        // Rule 1: OFFLINE
        ruleId1 = createRule("Rule 1 - OFFLINE", ContentTypeEnum.SCRIPT, RuleStatusEnum.OFFLINE, "return amount > 50")

        // Rule 2: TEST
        ruleId2 = createRule("Rule 2 - TEST", ContentTypeEnum.SCRIPT, RuleStatusEnum.TEST, "return amount > 100")
        transitionRuleToStatus(ruleId2, RuleStatusEnum.TEST)

        // Rule 3: GRAY
        ruleId3 = createRule("Rule 3 - GRAY", ContentTypeEnum.SCRIPT, RuleStatusEnum.GRAY, "return amount > 150")
        transitionRuleToStatus(ruleId3, RuleStatusEnum.TEST)
        transitionRuleToStatus(ruleId3, RuleStatusEnum.GRAY)

        // Rule 4: AB_TEST (in group)
        ruleId4 = createRule("Rule 4 - AB_TEST", ContentTypeEnum.SCRIPT, RuleStatusEnum.AB_TEST, "return amount > 200")
        transitionRuleToStatus(ruleId4, RuleStatusEnum.TEST)
        transitionRuleToStatus(ruleId4, RuleStatusEnum.GRAY)
        transitionRuleToStatus(ruleId4, RuleStatusEnum.AB_TEST)

        // Rule 5: AB_TEST (in group)
        ruleId5 = createRule("Rule 5 - AB_TEST", ContentTypeEnum.SCRIPT, RuleStatusEnum.AB_TEST, "return amount > 250")
        transitionRuleToStatus(ruleId5, RuleStatusEnum.TEST)
        transitionRuleToStatus(ruleId5, RuleStatusEnum.GRAY)
        transitionRuleToStatus(ruleId5, RuleStatusEnum.AB_TEST)

        // Rule 6: FULL
        ruleId6 = createRule("Rule 6 - FULL", ContentTypeEnum.SCRIPT, RuleStatusEnum.FULL, "return amount > 300")
        transitionRuleToStatus(ruleId6, RuleStatusEnum.TEST)
        transitionRuleToStatus(ruleId6, RuleStatusEnum.GRAY)
        transitionRuleToStatus(ruleId6, RuleStatusEnum.AB_TEST)
        transitionRuleToStatus(ruleId6, RuleStatusEnum.FULL)

        // Create rule group with rule 4 and rule 5
        // Note: When rule4 transitions to AB_TEST, a group is automatically created
        def rule4 = ruleService.getRuleById(ruleId4)
        def groupId = rule4.getRuleGroupId()
        assert groupId != null : "Rule 4 should have a group ID after transitioning to AB_TEST"

        // Add rule 5 to the same group
        def rule5 = ruleService.getRuleById(ruleId5)
        // If rule5 already has a group (created when transitioning to AB_TEST), we need to handle it
        if (rule5.getRuleGroupId() != null && rule5.getRuleGroupId() != groupId) {
            // Remove rule5 from its current group and add to rule4's group
            // First, set rule5 to OFFLINE to remove it from its group
            def rule5Offline = Rule.builder()
                    .id(rule5.getId())
                    .name(rule5.getName())
                    .contentType(rule5.getContentType())
                    .content(rule5.getContent())
                    .description(rule5.getDescription())
                    .ruleStatus(RuleStatusEnum.OFFLINE)
                    .ruleGroupId(null)
                    .build()
            ruleService.updateRule(ruleId5, rule5Offline)
            // Then transition back to AB_TEST with the target groupId (OFFLINE -> TEST -> GRAY -> AB_TEST)
            transitionRuleToStatus(ruleId5, RuleStatusEnum.TEST)
            transitionRuleToStatus(ruleId5, RuleStatusEnum.GRAY)
            // Update rule5 to AB_TEST with target groupId
            rule5 = ruleService.getRuleById(ruleId5)
            def rule5ABTest = Rule.builder()
                    .id(rule5.getId())
                    .name(rule5.getName())
                    .contentType(rule5.getContentType())
                    .content(rule5.getContent())
                    .description(rule5.getDescription())
                    .ruleStatus(RuleStatusEnum.AB_TEST)
                    .ruleGroupId(groupId)
                    .build()
            ruleService.updateRule(ruleId5, rule5ABTest)
        } else if (rule5.getRuleGroupId() == null) {
            // Add rule 5 to the group
            ruleGroupService.addRuleToGroup(rule5, groupId)
        }

        // Update rule group with ratios: rule4=10, rule5=50
        // Note: Both rules must already be in AB_TEST status and in the group
        def rules = [(ruleId4): 10, (ruleId5): 50]
        ruleGroupService.updateRuleGroupWithRules(groupId, rules)

        // Create event-rule associations
        // Event 16000001: with some rules (rule2, rule3)
        createRuleEventRelation(EVENT_ID_1, ruleId2, 1)
        createRuleEventRelation(EVENT_ID_1, ruleId3, 2)

        // Event 16000002: with all rules and rule group
        createRuleEventRelation(EVENT_ID_2, ruleId1, 1)
        createRuleEventRelation(EVENT_ID_2, ruleId2, 2)
        createRuleEventRelation(EVENT_ID_2, ruleId3, 3)
        createRuleEventRelation(EVENT_ID_2, ruleId6, 4)
        createGroupEventRelation(EVENT_ID_2, groupId, 5)

        // Event 16000003: no rules (already handled in test)
    }

    private void createEvent(Long eventId, String name) {
        eventService.createEvent(eventId, name, "Test event: ${name}")
    }

    private Long createRule(String name, ContentTypeEnum type, RuleStatusEnum status, String content) {
        def rule = Rule.builder()
                .id(null)  // Let database auto-generate ID
                .name(name)
                .contentType(type)
                .ruleStatus(status)
                .content(content)
                .description("Test rule: ${name}")
                .build()
        ruleService.createRule(rule)
        return rule.getId()
    }

    private void transitionRuleToStatus(Long ruleId, RuleStatusEnum targetStatus) {
        def rule = ruleService.getRuleById(ruleId)
        if (rule == null) {
            throw new IllegalArgumentException("Rule not found: ${ruleId}")
        }
        def ruleToUpdate = Rule.builder()
                .id(rule.getId())
                .name(rule.getName())
                .contentType(rule.getContentType())
                .content(rule.getContent())
                .description(rule.getDescription())
                .ruleStatus(targetStatus)
                .ruleGroupId(rule.getRuleGroupId())
                .build()
        ruleService.updateRule(ruleId, ruleToUpdate)
    }

    private void createRuleEventRelation(Long eventId, Long ruleId, Integer order) {
        def relation = new ExecutionEventRelationEntity()
        relation.setEventId(eventId)
        relation.setItemType(ExecutionItemTypeEnum.RULE.getId())
        relation.setItemId(ruleId)
        relation.setExecutionOrder(order)
        long currentTime = (long) (System.currentTimeMillis() / 1000)
        relation.setCt((int) currentTime)
        relation.setUt((int) currentTime)
        executionEventRelationMapper.insert(relation)
    }

    private void createGroupEventRelation(Long eventId, Long groupId, Integer order) {
        def relation = new ExecutionEventRelationEntity()
        relation.setEventId(eventId)
        relation.setItemType(ExecutionItemTypeEnum.RULE_GROUP.getId())
        relation.setItemId(groupId)
        relation.setExecutionOrder(order)
        long currentTime = (long) (System.currentTimeMillis() / 1000)
        relation.setCt((int) currentTime)
        relation.setUt((int) currentTime)
        executionEventRelationMapper.insert(relation)
    }
}

