package lab.zhang.rule.rule_engine.controller

import com.baomidou.mybatisplus.core.conditions.query.QueryWrapper
import lab.zhang.rule.rule_engine.common.TypedValue
import lab.zhang.rule.rule_engine.entity.ExecutionArrangementEntity
import lab.zhang.rule.rule_engine.enums.ContentTypeEnum
import lab.zhang.rule.rule_engine.enums.RuleStatusEnum
import lab.zhang.rule.rule_engine.enums.ValueTypeEnum
import lab.zhang.rule.rule_engine.mapper.EventMapper
import lab.zhang.rule.rule_engine.mapper.ExecutionArrangementMapper
import lab.zhang.rule.rule_engine.mapper.RuleGroupMapper
import lab.zhang.rule.rule_engine.mapper.RuleMapper
import lab.zhang.rule.rule_engine.model.Event
import lab.zhang.rule.rule_engine.model.Rule
import lab.zhang.rule.rule_engine.pojo.dto.RuleDTO
import lab.zhang.rule.rule_engine.pojo.qo.EvalRequestQO
import lab.zhang.rule.rule_engine.service.EventService
import lab.zhang.rule.rule_engine.service.RuleGroupService
import lab.zhang.rule.rule_engine.service.RuleService
import lab.zhang.rule.rule_engine.util.LoggingContextUtil
import lab.zhang.rule.rule_engine.util.TimeUtil
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.boot.test.context.SpringBootTest
import org.springframework.http.HttpStatus
import org.springframework.test.context.ActiveProfiles
import org.springframework.transaction.annotation.Transactional
import spock.lang.Specification

/**
 * EvalController integration test
 * Tests the eval interface with real database and execution trace
 *
 * Prerequisites:
 * 1. MySQL database is running on localhost:3306
 * 2. Database 'rule_engine_test' exists
 * 3. Tables are created (see DATABASE_SCHEMA.md)
 *
 * @author Rongjin Zhang
 */
@SpringBootTest
@ActiveProfiles("test")
@Transactional
class EvalRequestControllerIntegrationSpec extends Specification {

    @Autowired
    private EvalController evalController

    @Autowired
    private EventService eventService

    @Autowired
    private RuleService ruleService

    @Autowired
    private RuleGroupService ruleGroupService

    @Autowired
    private EventMapper eventMapper

    @Autowired
    private RuleMapper ruleMapper

    @Autowired
    private RuleGroupMapper ruleGroupMapper

    @Autowired
    private ExecutionArrangementMapper executionArrangementMapper

    // Test data IDs
    private static final Integer EVENT_ID_1 = 16000001
    private static final Integer EVENT_ID_2 = 16000002
    private static final Integer EVENT_ID_3 = 16000003

    // Rule IDs (will be auto-generated by database)
    private Long ruleId1  // OFFLINE
    private Long ruleId2  // TEST
    private Long ruleId3  // GRAY
    private Long ruleId4  // ONLINE (group A)
    private Long ruleId5  // ONLINE (group A)
    private Long ruleId6  // ONLINE (any other group)
    private Long ruleId7  // ONLINE (any other group)

    def setup() {
        // Clean up test data before each test
        executionArrangementMapper.delete(null)
        ruleGroupMapper.delete(null)
        ruleMapper.delete(null)
        eventMapper.delete(null)

        // Setup test data
        setupTestData()
    }

    def "test eval interface - integration test with execution trace"() {
        given: "prepare eval request"
        def evalQO = new EvalRequestQO()
        evalQO.userId = 1000L
        evalQO.eventId = EVENT_ID_2
        evalQO.arguments = [
                "amount": new TypedValue(300.0, ValueTypeEnum.DECIMAL)
        ]

        when: "call eval interface"
        def response = evalController.eval(evalQO)

        then: "should return success response with execution trace"
        response.statusCode == HttpStatus.OK
        response.body != null
        response.body.result != null
        response.body.briefSteps != null
        response.body.briefSteps.size() > 0

        and: "should have passed GRAY rules for event 16000002"
        def trueValue = TypedValue.trueValue()
        response.body.briefSteps.get(trueValue) != null
        response.body.briefSteps.get(trueValue).size() > 0
        response.body.briefSteps.get(trueValue).get(0) != null
        response.body.briefSteps.get(trueValue).get(0).ruleId == ruleId3  // GRAY rule should evaluate to true
        response.body.briefSteps.get(trueValue).get(0).groupId != null
        response.body.briefSteps.get(trueValue).get(0).groupId == 0
        response.body.briefSteps.get(trueValue).get(0).errmsg == null

        and: "should have failed ONLINE rules for event 16000002"
        def falseValue = TypedValue.falseValue()
        response.body.briefSteps.get(falseValue) != null
        response.body.briefSteps.get(falseValue).size() > 0
        response.body.briefSteps.get(falseValue).get(0) != null
        response.body.briefSteps.get(falseValue).get(0).ruleId == ruleId7
        response.body.briefSteps.get(falseValue).get(0).groupId != null
        response.body.briefSteps.get(falseValue).get(0).groupId > 0
        response.body.briefSteps.get(falseValue).get(0).errmsg == null
    }

    def "test eval interface - multiple requests to analyze rule group selection distribution"() {
        given: "prepare multiple eval requests with random amount values"
        def requestCount = 1000
        def ruleSelectionCounts = [:]
        def totalExecutions = 0

        when: "call eval interface multiple times"
        requestCount.times { index ->
            def amount = Math.random() * 500  // Random amount between 0 and 500
            def evalQO = new EvalRequestQO()
            evalQO.userId = 1000L + index  // Different userId for each request
            evalQO.eventId = EVENT_ID_2
            evalQO.arguments = [
                    "amount": new TypedValue(amount, ValueTypeEnum.DECIMAL)
            ]

            def response = evalController.eval(evalQO)
            response.statusCode == HttpStatus.OK
            response.body != null
            response.body.result != null
            response.body.briefSteps != null
            response.body.briefSteps.size() > 0

            and: "may have passed some rules"
            def trueValue = TypedValue.trueValue()
            if (response.body.briefSteps.get(trueValue) != null && response.body.briefSteps.get(trueValue).size() > 0) {
                def passedSteps = response.body.briefSteps.get(trueValue)
                passedSteps.each { step ->
                    assert step.ruleId != null
                    assert step.groupId != null
                    assert step.errmsg == null
                    // count execution
                    totalExecutions++
                    // count selection if rule group
                    if (step.groupId != 0) {
                        def selectedRuleId = step.ruleId
                        ruleSelectionCounts[selectedRuleId] = (ruleSelectionCounts[selectedRuleId] ?: 0) + 1
                    }
                }
            }

            and: "may have failed some rules"
            def falseValue = TypedValue.falseValue()
            if (response.body.briefSteps.get(falseValue) != null && response.body.briefSteps.get(falseValue).size() > 0) {
                def failedSteps = response.body.briefSteps.get(falseValue)
                failedSteps.each { step ->
                    assert step.ruleId != null
                    assert step.groupId != null
                    assert step.errmsg == null
                    // count execution
                    totalExecutions++
                    // count selection if rule group
                    if (step.groupId != 0) {
                        def selectedRuleId = step.ruleId
                        ruleSelectionCounts[selectedRuleId] = (ruleSelectionCounts[selectedRuleId] ?: 0) + 1
                    }
                }
            }
        }

        then: "should have execution traces for all requests"
        totalExecutions > 0

        and: "rule group selection should follow probability distribution"
        // Rule group has 2 rules with ratios 10 and 50 (total 60, leaving 40% for no selection)
        // Expected distribution: rule4 ~10%, rule5 ~50%, no selection ~40%
        if (totalExecutions > 0) {
            def rule4Count = ruleSelectionCounts[ruleId4] ?: 0
            def rule5Count = ruleSelectionCounts[ruleId5] ?: 0
            def rule4Percentage = (rule4Count / totalExecutions) * 100
            def rule5Percentage = (rule5Count / totalExecutions) * 100
            def noSelectionPercentage = ((totalExecutions - rule4Count - rule5Count) / totalExecutions) * 100

            println "Rule Group Selection Distribution (${totalExecutions} executions):"
            println "  Rule ${ruleId4} (ratio 10): ${rule4Count} times (${String.format("%.2f", rule4Percentage)}%)"
            println "  Rule ${ruleId5} (ratio 50): ${rule5Count} times (${String.format("%.2f", rule5Percentage)}%)"
            println "  No selection: ${totalExecutions - rule4Count - rule5Count} times (${String.format("%.2f", noSelectionPercentage)}%)"

            // Allow some variance (within 5% of expected)
            rule4Percentage >= 5 && rule4Percentage <= 15  // Expected ~10%
            rule5Percentage >= 45 && rule5Percentage <= 55  // Expected ~50%
            noSelectionPercentage >= 35 && noSelectionPercentage <= 45  // Expected ~40%
        } else {
            // If no executions, it might be because environment doesn't allow ONLINE rules
            println "Warning: No rule group executions found. This might be due to environment configuration."
            // In GRAY environment, ONLINE rules should execute, so this should not happen
            assert false: "Expected rule group executions but found none. Check environment configuration."
        }
    }

    def "test eval interface - event with no rules should return null result"() {
        given: "prepare eval request for event with no rules"
        def evalQO = new EvalRequestQO()
        evalQO.userId = 1000L
        evalQO.eventId = EVENT_ID_3
        evalQO.arguments = [
                "amount": new TypedValue(150.0, ValueTypeEnum.DECIMAL)
        ]

        when: "call eval interface"
        def response = evalController.eval(evalQO)

        then: "should return null result"
        response.statusCode == HttpStatus.OK
        response.body != null
        response.body.result != null
        response.body.result.value == null
        response.body.briefSteps != null
        response.body.briefSteps.size() == 0
    }

    def "test eval interface - execution trace details"() {
        given: "prepare eval request"
        def evalQO = new EvalRequestQO()
        evalQO.userId = 1000L
        evalQO.eventId = EVENT_ID_2
        evalQO.arguments = [
                "amount": new TypedValue(150.0, ValueTypeEnum.DECIMAL)
        ]

        when: "call eval interface"
        def response = evalController.eval(evalQO)

        then: "execution trace should contain detailed information"
        response.statusCode == HttpStatus.OK
        def briefSteps = response.body.briefSteps
        briefSteps != null

        and: "should passed some rules"
        def trueValue = TypedValue.trueValue()
        if (briefSteps.get(trueValue) != null && briefSteps.get(trueValue).size() > 0) {
            def passedSteps = briefSteps.get(trueValue)
            passedSteps.each { step ->
                assert step.ruleId != null
                assert step.groupId != null
                assert step.result != null
                assert step.result.value == true
                assert step.errmsg == null
            }
        }

        and: "should failed some rules"
        def falseValue = TypedValue.trueValue()
        if (briefSteps.get(falseValue) != null && briefSteps.get(falseValue).size() > 0) {
            def failedSteps = briefSteps.get(falseValue)
            failedSteps.each { step ->
                assert step.ruleId != null
                assert step.groupId != null
                assert step.result != null
                assert step.result.value == false
                assert step.errmsg == null
            }
        }
    }

    def "test eval interface - cache control via RULE_CONTENT_CACHE_ENABLED environment variable"() {
        given: "prepare eval request"
        def evalQO = new EvalRequestQO()
        evalQO.userId = 1000L
        evalQO.eventId = EVENT_ID_2
        evalQO.arguments = [
                "amount": new TypedValue(300.0, ValueTypeEnum.DECIMAL)
        ]

        when: "call eval interface with cache enabled (default)"
        def responseWithCache = evalController.eval(evalQO)

        then: "should return success response"
        responseWithCache.statusCode == HttpStatus.OK
        responseWithCache.body != null
        responseWithCache.body.result != null

        when: "call eval interface again with same parameters (should use cache)"
        def responseWithCacheAgain = evalController.eval(evalQO)

        then: "should return same result"
        responseWithCacheAgain.statusCode == HttpStatus.OK
        responseWithCacheAgain.body != null
        responseWithCacheAgain.body.result != null

        // Note: In integration test, we can't easily verify cache behavior without mocking,
        // but this test ensures the interface works correctly with cache configuration
        // In a real environment, RULE_CONTENT_CACHE_ENABLED=false would bypass cache
    }

    // Helper methods
    private void setupTestData() {
        // Create 3 events
        createEvent(EVENT_ID_1, "Event 1")
        createEvent(EVENT_ID_2, "Event 2")
        createEvent(EVENT_ID_3, "Event 3")

        // Create 6 rules with different statuses
        // Rule 1: OFFLINE
        ruleId1 = createRule("Rule 1 - OFFLINE", ContentTypeEnum.SCRIPT, RuleStatusEnum.OFFLINE, "return amount >= 100")

        // Rule 2: TEST
        ruleId2 = createRule("Rule 2 - TEST", ContentTypeEnum.SCRIPT, RuleStatusEnum.OFFLINE, "return amount >= 200")
        createExecutionArrangement(EVENT_ID_2, ruleId2, 0L, 0, 0)
        transitionRuleToStatus(ruleId2, RuleStatusEnum.TEST)

        // Rule 3: GRAY
        ruleId3 = createRule("Rule 3 - GRAY", ContentTypeEnum.SCRIPT, RuleStatusEnum.OFFLINE, "return amount >= 300")
        createExecutionArrangement(EVENT_ID_2, ruleId3, 0L, 1, 0)
        transitionRuleToStatus(ruleId3, RuleStatusEnum.TEST)
        transitionRuleToStatus(ruleId3, RuleStatusEnum.GRAY)

        // Rule 4: ONLINE (in group)
        ruleId4 = createRule("Rule 4 - ONLINE", ContentTypeEnum.SCRIPT, RuleStatusEnum.OFFLINE, "return amount >= 400")
        // Create event association before transitioning to ONLINE so createRuleGroup can find it
        createExecutionArrangement(EVENT_ID_2, ruleId4, 0L, 2, 0)
        // Verify the event-rule relation was created
        def rule4ArrangementEntity = executionArrangementMapper.selectOne(
                new QueryWrapper<ExecutionArrangementEntity>()
                        .eq("rule_id", ruleId4)
                        .eq("event_id", EVENT_ID_2)
        )
        assert rule4ArrangementEntity != null: "Rule 4 should have event-rule relation before transitioning to ONLINE. RuleId: ${ruleId4}, EventId: ${EVENT_ID_2}"
        transitionRuleToStatus(ruleId4, RuleStatusEnum.TEST)
        transitionRuleToStatus(ruleId4, RuleStatusEnum.GRAY)
        // Re-verify event-rule relation still exists before transitioning to ONLINE
        def rule4ArrangementEntityBeforeOnline = executionArrangementMapper.selectOne(
                new QueryWrapper<ExecutionArrangementEntity>()
                        .eq("rule_id", ruleId4)
                        .eq("event_id", EVENT_ID_2)
        )
        assert rule4ArrangementEntityBeforeOnline != null: "Rule 4 should still have event-rule relation before transitioning to ONLINE. RuleId: ${ruleId4}, EventId: ${EVENT_ID_2}"
        transitionRuleToStatus(ruleId4, RuleStatusEnum.ONLINE)
        def rule4ArrangementEntityAfterOnline = executionArrangementMapper.selectOne(
                new QueryWrapper<ExecutionArrangementEntity>()
                        .eq("rule_id", ruleId4)
                        .eq("event_id", EVENT_ID_2)
        )
        def groupId4 = rule4ArrangementEntityAfterOnline.getGroupId()

        // Rule 5: ONLINE (in group)
        RuleDTO rule5DTO = new RuleDTO(null, "Rule 5 - ONLINE", "", ContentTypeEnum.SCRIPT.getId(), "return amount >= 500", RuleStatusEnum.OFFLINE.getId())
        def rule5 = ruleGroupService.copyRuleInGroup(ruleId4, rule5DTO)
        ruleId5 = rule5.getId()

        def rule4ArrangementEntityAfterCopy = executionArrangementMapper.selectOne(
                new QueryWrapper<ExecutionArrangementEntity>()
                        .eq("rule_id", ruleId4)
                        .eq("event_id", EVENT_ID_2)
        )
        def rule5ArrangementEntityAfterCopy = executionArrangementMapper.selectOne(
                new QueryWrapper<ExecutionArrangementEntity>()
                        .eq("rule_id", ruleId5)
                        .eq("event_id", EVENT_ID_2)
        )

        // Rule 6: ONLINE
        ruleId6 = createRule("Rule 6 - ONLINE", ContentTypeEnum.SCRIPT, RuleStatusEnum.OFFLINE, "return amount >= 600")
        createExecutionArrangement(EVENT_ID_2, ruleId6, 0L, 3, 0)
        transitionRuleToStatus(ruleId6, RuleStatusEnum.TEST)
        transitionRuleToStatus(ruleId6, RuleStatusEnum.GRAY)
        transitionRuleToStatus(ruleId6, RuleStatusEnum.ONLINE)

        // Rule 7: ONLINE
        ruleId7 = createRule("Rule 7 - ONLINE", ContentTypeEnum.SCRIPT, RuleStatusEnum.OFFLINE, "return amount >= 700")
        createExecutionArrangement(EVENT_ID_2, ruleId7, 0L, 4, 0)
        transitionRuleToStatus(ruleId7, RuleStatusEnum.TEST)
        transitionRuleToStatus(ruleId7, RuleStatusEnum.GRAY)
        transitionRuleToStatus(ruleId7, RuleStatusEnum.ONLINE)
        def rule7ArrangementEntityAfterOnline = executionArrangementMapper.selectOne(
                new QueryWrapper<ExecutionArrangementEntity>()
                        .eq("rule_id", ruleId7)
                        .eq("event_id", EVENT_ID_2)
        )
        def groupId7 = rule7ArrangementEntityAfterOnline.getGroupId()

        // Update ratios for rule4, rule5 and rule7
        ruleGroupService.updateRuleGroupRatios(groupId4, [(ruleId4): 10, (ruleId5): 50])
        ruleGroupService.updateRuleGroupRatios(groupId7, [(ruleId7): 100])

        // Event 16000003: no rules (already handled in test)
    }

    private void createEvent(Integer eventId, String name) {
        Event event = Event.builder()
                .id(eventId)
                .name(name)
                .description("Test event: ${name}")
                .build()
        eventService.createEvent(event)
    }

    private Long createRule(String name, ContentTypeEnum type, RuleStatusEnum status, String content) {
        def rule = Rule.builder()
                .id(null)  // Let database auto-generate ID
                .name(name)
                .contentType(type)
                .ruleStatus(status)
                .content(content)
                .description("Test rule: ${name}")
                .build()
        ruleService.createRule(rule)
        return rule.getId()
    }

    private void createExecutionArrangement(Integer eventId, Long ruleId, Long groupId, Integer exeOrder, Integer abRatio) {
        def relation = new ExecutionArrangementEntity()
        relation.setEventId(eventId)
        relation.setRuleId(ruleId)
        relation.setGroupId(groupId != null ? groupId : 0L)
        relation.setExeOrder(exeOrder != null ? exeOrder : 0)
        relation.setAbRatio(abRatio != null ? abRatio : 0)
        long currentTime = (long) (TimeUtil.getCurrentTime())
        relation.setCt((int) currentTime)
        relation.setUt((int) currentTime)
        executionArrangementMapper.insert(relation)
    }

    private void transitionRuleToStatus(Long ruleId, RuleStatusEnum targetStatus) {
        def rule = ruleService.getRuleById(ruleId)
        if (rule == null) {
            throw new IllegalArgumentException("Rule not found: ${ruleId}")
        }
        def ruleToUpdate = Rule.builder()
                .id(rule.getId())
                .name(rule.getName())
                .contentType(rule.getContentType())
                .content(rule.getContent())
                .description(rule.getDescription())
                .ruleStatus(targetStatus)
                .build()
        ruleService.updateRule(ruleId, ruleToUpdate)
    }
}


